### ISSUE TITLE
Cannot run in server mode (development)

### ISSUE THREAD

**Issue by adrianofoschi** [felixfbecker/vscode-php-debug#109]
I'm trying to start vs-code-php-debug in server mode. 
The first error that occured is: "/out dir in OutDir does not exist". I solved it by creating the folder.
Now the error is "Get error: Cannot launch program 'phpDebug.ts'; setting the 'outFiles' attribute might help. I setted it but the error persists.

My actually launch.json config
```json
      "name": "Debug adapter",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/src/phpDebug.ts",
      "cwd": "${workspaceRoot}",
      "args": ["--server=4711"],
      "env": {
        "NODE_ENV": "development"
      },
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/out",
      "outFiles": [ "${workspaceRoot}/out/**/*.js" ]
```

**Comment by felixfbecker** [comment]
Did you compile?

> The extension is written in TypeScript and compiled using a Gulpfile that first transpiles to ES6 and then uses Babel to specifically target VS Code's Node version. You can run the compile task through npm run compile, gulp compile or from VS Code with Ctrl+Shift+B. npm run watch / gulp watch enables incremental compilation.

**Comment by adrianofoschi** [comment]
I didn't compile it sorry. Thanks you.
