### ISSUE TITLE
How to debug a drush task

### ISSUE THREAD

**Issue by diego4serve** [felixfbecker/vscode-php-debug#122]
Hi Felix, thanks for your amazing work on this extension, can you explain me if is it possible to debug a drush command if yes tell me how. I've searched in google, all post i see refers to an option idekey I don't know if is mandatory to setup and if it is a requirement. Thanks in advance

**Comment by felixfbecker** [comment]
What is a drush command?

**Comment by diego4serve** [comment]
I'm not an expert I'm starting on php development. What i know is that Drush is a shell based tool for Drupal that let you create tasks for update or import data or maintenance tasks.For example I can create a module that contains one or many functions and then in terminal in the drupal's  docrroot I can type 

$ drush <name_of_the_fuction>

To run a given task

**Comment by felixfbecker** [comment]
If you can find a PHP file that gets executed for drush, you can modify the "Launch file" configuration with `program` and `args`.
Otherwise just "Listen for XDebug", set your breakpoints and run the task.

**Comment by cogentParadigm** [comment]
I know this is closed but it doesn't work. Drush actually hangs until i stop the debugger. PHPStorm has the same issue but it can be fixed via settings in PHPStorm. Here is an issue describing the fix in PHPStorm https://github.com/drush-ops/drush/issues/1534
