### ISSUE TITLE
Remote

### ISSUE THREAD

**Issue by pitylee** [felixfbecker/vscode-php-debug#125]
Hello there

So I enabled xdebug with remote trigger on local and remote server, and I succeeded to debug onthe local machine, but on the remote machine it doesn't seem to work.
I tried messing with iptables on my ubuntu machine and trying to redirect port 9009 to ip:9000 on remote server but no luck, when I trace 9009 it redirects to self host.
How could I give a host or IP in the json file in order to try and debug on remote machine (port forwarding and firewall are set up as they should.)

Thanks,
P

**Comment by felixfbecker** [comment]
That is not set in the launch.json, but in your php.ini. See remote_host

**Comment by pitylee** [comment]
but how will the code know that it has to connect to what xdebug says to it when there's no direct connection to the remote php server?

**Comment by felixfbecker** [comment]
VS Code does not connect to XDebug, XDebug connects to VS Code

**Comment by pitylee** [comment]
zend_extension=xdebug.so
zend_optimizerplus.load_comments=1
xdebug.auto_trace=1
xdebug.dump_undefined=1
xdebug.extended_info=1
xdebug.profiler_enable=1
xdebug.profiler_enable_trigger=1
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_host=94.52.52.99
xdebug.remote_port=9000
xdebug.remote_connect_back=1
xdebug.scream=0
xdebug.show_error_trace=1
xdebug.collect_assignments=1
xdebug.collect_includes=1
xdebug.collect_params=1
xdebug.show_error_trace=1
xdebug.show_exception_trace=1
xdebug.show_mem_delta=1

**Comment by pitylee** [comment]
94.52.52.99 is the remote server
94.52.51.144 is my ubuntu machine's external ip

**Comment by felixfbecker** [comment]
Sorry, can't help you
