### ISSUE TITLE
Provide slightly clearer example of remote debugging configuration

### ISSUE THREAD

**Issue by tedmasterweb** [felixfbecker/vscode-php-debug#143]
This is just a tiny suggestion that perhaps under Remote Host Debugging you could change 

```
"localSourceRoot": "${workspaceRoot}/public"
```

to something like
```
"localSourceRoot": "/path/on/local/machine/to/public"
```

workspaceRoot is "the path of the folder opened in VS Code"
https://code.visualstudio.com/docs/editor/tasks#_variable-substitution

Since I work on a number of projects with multiple folders and subfolders, it's actually unlikely that I would want workspaceRoot. Rather, I would want web server document root (but there doesn't seem to be a variable for that…)

Thanks for the AWESOME extension!

**Comment by felixfbecker** [comment]
Normally you would configure your webserver to serve your project's public folder under a specific URL. If the folder being served is not open in your workspace, why/how would you want to debug it?

**Comment by tedmasterweb** [comment]
>If the folder being served is not open in your workspace, why/how would you want to debug it?

Given:
path to local document root: 
/Users/me/Sites/vagrant/public

path to server document root: 
/var/www/public

path to local WordPress project: 
/Users/me/Sites/vagrant/public/wp

path to local WordPress project theme: 
/Users/me/Sites/vagrant/public/wp/wp-content/themes/silly-theme-child

If I open the theme folder (because that is what I'm working on, not the entire WordPress installation), ${workspaceRoot} contains:
/Users/me/Sites/vagrant/public/wp/wp-content/themes/silly-theme-child

And VS Code returns the error (because it caught an exception in a plugin):
>Unable to open 'wp-some-plugin.php': File not found (/Users/me/Sites/vagrant/public/wp/wp-content/themes/silly-theme-child/wp/wp-content/plugins/wp-some-plugin/wp-some-plugin.php).

Because the path is invalid (the error should be obvious).

I realize I could open the main WordPress folder and things should work as expected, but my suggestion was to try and make the already excellent documentation just a bit clearer, less ambiguous, by removing a variable from the equation.

HTH

**Comment by felixfbecker** [comment]
The idea behing using `${workspaceRoot}` is not couple your config to a machine so you can commit it and share across coworkers.
Usually there is a 1:1:1 mapping between VS Code instance : project : repository, so I'm gonna leave it like this as I think this is the most common use case.
