### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by slifin** [felixfbecker/vscode-php-debug#147]
Is this a known limitation? 

<img width="920" alt="screen shot 2017-03-07 at 10 13 33" src="https://cloud.githubusercontent.com/assets/198857/23651909/ef129612-031e-11e7-804c-537103538883.png">

`            "xdebugSettings": {
                "max_children": 4000,
                "max_data": 104857600,
                "max_depth": 4000
            }`

**Comment by felixfbecker** [comment]
That is XDebugs infinite recursion protection, set `xdebug.max_nesting_level` in php.ini.
