### ISSUE TITLE
php debug does not work with ver 1.1.2

### ISSUE THREAD

**Issue by wuceyang** [felixfbecker/vscode-php-debug#15]
hi,@felixfbecker ,I think there must be something wrong in my config or php-debug.
The server is centos with vmare,which shares folders with windows.
The php-debug config file:
```javascript
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9000,
            "serverSourceRoot":"/mnt/web/app",
            "localSourceRoot": "./",
            "log": true
		}
	]
}
```
the vsc opened "d:/Web/app", which is mapped "/mnt/web/app" on server
I set breakpoints in file EconomyController.php, and the start debug listening.when i sent request to server,the debug console show logs below:
```javascript
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 3 } }
-> threadsRequest
{ type: 'request', seq: 9, command: 'threads' }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 9,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 3, name: 'Request 3 (7:00:09 PM)' } ] } }
<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }
-> setBreakpointsRequest
{ type: 'request',
  seq: 10,
  command: 'setBreakpoints',
  arguments: 
   { source: { path: 'd:\\Web\\app\\app\\Http\\Controllers\\Im\\EconomyController.php' },
     lines: [ 118, 119 ] } }
-> setExceptionBreakpointsRequest
{ type: 'request',
  seq: 11,
  command: 'setExceptionBreakpoints',
  arguments: { filters: [] } }
<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 11,
  command: 'setExceptionBreakpoints',
  success: true }
<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'setBreakpoints',
  success: true,
  body: 
   { breakpoints: 
      [ Breakpoint { verified: true, line: 118 },
        Breakpoint { verified: true, line: 119 } ] } }
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'exited', threadId: 3 } }
```
and browser got results quickly, not stopped at the breakpoints.
the path in the log is correct
xdebug configure:
zend_extension=xdebug.so
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = "192.168.0.114"
xdebug.remote_port = 9000
;xdebug.remote_handler = "dbgp"
;xdebug.remote_mode = req
xdebug.remote_connect_back = 1
xdebug.idekey="mydebug"
xdebug.max_nesting_level = 512
xdebug.remote_log = "/var/log/xdebug.log"

the php debug version is 1.1.2
can you tell me where i made mistakes? thanks

**Comment by felixfbecker** [comment]
Could you please place a `phpinfo();` statement in your file and post the results in a [gist](https://gist.github.com/) (it will get truncated otherwise)?

Also, do you get any output in /var/log/xdebug.log?

**Comment by wuceyang** [comment]
thank you,i'll post the information here tomorrow.the environment is in my office pc.

**Comment by wuceyang** [comment]
there is a lot of php extensions,so the browser page is huge. this is xdebug info below:

![1](https://cloud.githubusercontent.com/assets/1538757/12469292/9ea9a126-c025-11e5-86f9-608caa9c73f4.png)

![2](https://cloud.githubusercontent.com/assets/1538757/12469296/a4482b5c-c025-11e5-9c71-a1258c352037.png)

here is my php basic infomation:

![image](https://cloud.githubusercontent.com/assets/1538757/12469318/cab6d57c-c025-11e5-9bf7-f334a64f7680.png)

xdebug log file:
[xdebug.txt](https://github.com/felixfbecker/vscode-php-debug/files/98549/xdebug.txt)

if you need more, i'will show you next time.thanks

**Comment by felixfbecker** [comment]
Could you tell me some info about your folder structure?
From the logs, I see the requested entry point is `/mnt/web/app/artisan` (without a php extension, kind of weird), but breakpoints are set for `/mnt/web/app/app/Http/Controllers/Im/EconomyController.php`. Is the double `app` in the path correct?`

Could you maybe run `tree` command in your folder and paste your output?

**Comment by felixfbecker** [comment]
> the vsc opened "d:/Web/app", which is mapped "/mnt/web/app" on server

VS Code also reports `'d:\Web\app\app\Http\Controllers\Im\EconomyController.php`, so it seems to me you are missing a double `app` in your `serverSourceRoot`. Try setting `serverSourceRoot` to `/mnt/web/app/app`.

**Comment by wuceyang** [comment]
"/mnt/web/app" is the root path of the project which is created manually, and "/mnt/web/app/app" is the project subdirectory create by laravel. so the "/mnt/web/app" on linux is mapped "d:/Web/app". 
vsc opened "d:/Web/app", i think the param "serverSourceRoot" is "/mnt/web/app" is correct

**Comment by wuceyang** [comment]
[tree.txt](https://github.com/felixfbecker/vscode-php-debug/files/99034/tree.txt)

attachment is created by following command:
```shell
cd /mnt/web/app
tree -d -o /root/tree.txt
```

**Comment by felixfbecker** [comment]
I see, makes sense. So the file `/mnt/web/app/app/Http/Controllers/Im/EconomyController.php` actually exists? Because we get a perfect connection to XDebug and set a breakpoint for this file, then run...

Could you maybe try to write a dead simple test.php with just a few echo statements or something like that and try to debug that?

**Comment by felixfbecker** [comment]
So the only reason could be that the debugger never reaches the breakpoint (file not included, function not called, etc)

**Comment by wuceyang** [comment]
yes, it works in test.php with following codes
```php
    date_default_timezone_set("Asia/Chongqing");
    
    $a = 1;
    $b = 3;
    $c = $a + $b;
    echo $c;
```
this time i request test.php directly.
but in my project, the url is rewrite by nginx. maybe this is the problem?

**Comment by felixfbecker** [comment]
No, under what URL your webserver provides the project is irrelevant, XDebug always sends the real file path.

Like I said, I assume wherever you set your breakpoint is simply not reached. You may try to set a breakpoint in your entry point (front controller) and then use step over / step in to follow the execution.

**Comment by wuceyang** [comment]
thank you.there must be something wrong in my code.
i set breakpint in entry file, it wrorks fine.
