### ISSUE TITLE
Feature request: display class methods

### ISSUE THREAD

**Issue by QwertyZW** [felixfbecker/vscode-php-debug#156]
Adapter version:  https://github.com/felixfbecker/vscode-php-debug/commit/74f566250ad565e73753eb427fd02c0ce41c4a40

List methods/functions of a class when it's evaled/displayed

At the moment only properties specific to the class are shown and usually when working with large frameworks [such as this one](https://github.com/magento/magento2) the methods are a lot more relevant than the properties.

I've briefly gone through the dbgp protocol and I haven't seen anything that can be used to achieve this other than the eval command.

Retrieving class methods can be simulated with the eval command can be used to evaluate `get_class_methods($obj)` to retrieve the functions/methods of said class. 

![featurerequest](https://cloud.githubusercontent.com/assets/8478946/24535227/c46aea92-15a0-11e7-9eea-3658f5ccbe3d.png)

**Comment by felixfbecker** [comment]
I don't understand what exactly you are proposing

**Comment by QwertyZW** [comment]
I would like to have a class's methods displayed under the locals section or when it's evaled,

In a typescript/js context for example you'd have a __proto__ property that lists all the methods.
I'd like to have the same thing for php classes. 

I'm not sure whether this possible via the cs code debugger API; I see variableRequest's implementation but I'm not sure if it has something like methodsRequest, or if you might have to add a psuedo property to the object that contains all the methods.

I was simply suggesting a way to retrieve a given object's methods, but I don't know how you could approach surfacing them to the frontend.

**Comment by felixfbecker** [comment]
Imo this would mess with the semantics of the Variables panel. I personally never needed this tbh, this is more the job of IntelliSense (jump to definition, hover). I suggest you simply execute `get_class_methods` in the debug console when you need it.

**Comment by QwertyZW** [comment]
The problem with php intellisense and framewoks like magento and other frameworks that generate compiled code or attempt to do things like dependency injection is that php intellisense often fails to locate a given class if it's generated code, the 'go to definition' feature is a hit and miss sometimes even with wordpress . I found this debug adapter to be a lot more powerful than php intellisense, not only when it comes to debugging, but also when exploring scopes and the code base  in general. Not to say that the debug adapter isn't complimented by intellisense though. 

I suggest you try using your extensions with magento2 and similar,more moderbn frameworks like laravel, if you really wanna see their limits.

For starters, on windows 10 the php intellisense extension crashes before it completes  a full work space scan. (On ubuntu it works fine though with 1.3G+ allocated)

Anyway, let's stay within scope and at least acknowledge that there's  a problem to be solved. I understand that the extension is partially limited by vscode and xdebug, but that shouldn't stop you from thinking out of the box and solving the problem at hand

**Comment by felixfbecker** [comment]
Do you have an example of another IDE that supports this and how it shows this in the UI?

**Comment by gruz** [comment]
The idea is like this http://joomla-book.ru/images/stories/blog/jdump/com_jdump_3.jpg

Currently to check which methods an object has I need to edit the code with `get_class_methods` which demands extrasteps. 

@felixfbecker suggests to  `jump to definition`. But when a class extends another class which extends ... and at several extends it uses traits it becomes extremely hard to see the list of the class methods.
