### ISSUE TITLE
Newbie Help: mysqli_connect Not Working In VSCode-PHP-Debug

### ISSUE THREAD

**Issue by rburtoff** [felixfbecker/vscode-php-debug#168]
Please help, trying to set up VSCode to debug PHP, but it doesn't seem to work. XDebug is loaded according to PHPInfo, and I used the wizard to get the correct .DLL file.

Script runs fine if I execute it in a browser, but the mysqli_connect call isn't recognized when I try to debug the script in VSCode. These two lines exist in my php.ini (uncommented):

extension=php_mysql.dll
extension=php_mysqli.dll

Error I get is the following:
Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in C:\wamp64\www\public_html\php\clear_tokens.php:14
Stack trace:
#0 {main}
  thrown in C:\wamp64\www\public_html\php\clear_tokens.php on line 14

Also, when I try to run PHP code in debug mode the debug control panel at the top only appears for a second, the bar at the bottom of the screen turns orange, then right back to blue again. Can't seem to get into a "step into" mode for debugging.

Any and all help appreciated!

PHP version:  5.6.25
XDebug version:  2.5.4
Adapter version:  Unknown

Your launch.json:  
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "stopOnEntry": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "stopOnEntry": true
        }
    ]
}

XDebug php.ini config:  
; XDEBUG Extension
[xdebug]
zend_extension = "C:\wamp64\bin\php\php5.6.25\ext\php_xdebug-2.5.4-5.6-vc11-x86_64.dll"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1;
xdebug.profiler_enable = off
xdebug.profiler_enable_trigger = off
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.profiler_output_dir ="c:/wamp64/tmp"
xdebug.show_local_vars=0

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  NONE

Adapter logfile (from setting `"log": true` in launch.json):  NONE

Code snippet to reproduce:  
// Open a database connection
$dbconn = mysqli_connect('localhost', '[username]', '[password]', '[DB name]');
// Return either an open database connection or an error message
if (!is_object($dbconn)){
	$error_text = 'Error making database connection. Error text: ' . mysqli_connect_error($dbconn);
}

**Comment by felixfbecker** [comment]
That is a bug in your application, it crashes because you probably don't have mysqli enabled in php.ini. If you need more help please look at StackOverflow

**Comment by rburtoff** [comment]
Thanks!

___________________________
Ray Burtoff
(856) 816-6117
burtoff@yahoo.com

**Comment by rburtoff** [comment]
According to my PHPInfo output, mysqli is enabled, and as I already stated the file runs fine when executed directly through a browser. Not sure what's happening here, but I think I have a configuration problem in VSCode...

Thanks!

___________________________
Ray Burtoff
(856) 816-6117
burtoff@yahoo.com

**Comment by felixfbecker** [comment]
Are you using "Run currently open script"?

**Comment by rburtoff** [comment]
I've tried both; "Launch currently open script" and "Listen for XDebug". The "Listen" doesn't really do anything (I'm sure I'm missing a  command or something), but I get the error listed when I use "Launch currently open script". The debug stops immediately.
Thanks!

Ray Burtoff
(856) 816-6117
burtoff@yahoo.com


On Thursday, June 1, 2017, 7:26:40 PM EDT, Felix Becker <notifications@github.com> wrote:


Are you using "Run currently open script"?

**Comment by felixfbecker** [comment]
Launch currently open script will not work if you are debugging a browser application.
Listen for XDebug still requires you to open the page in your browser. Please refer to the Readme and XDebug documentation.

**Comment by rburtoff** [comment]
This script really isn't a browser application, it's a file I run as a CRON job to clear data from a table in my DB. I open it in a browser to get the Apache server to run the PHP code; nothing actually comes up on the page.
I know I'm probably doing something wrong, and I don't want to waste your time, but being able to step through PHP code would be an unbelievable help.
Thanks!

Ray Burtoff
(856) 816-6117
burtoff@yahoo.com


On Thursday, June 1, 2017, 7:40:35 PM EDT, Felix Becker <notifications@github.com> wrote:


Launch currently open script will not work if you are debugging a browser application.
Listen for XDebug still requires you to open the page in your browser. Please refer to the Readme and XDebug documentation.

**Comment by felixfbecker** [comment]
Note that there are often different php.ini for browser and CLI. If your browser shows mysqli is enabled that doesn't mean CLI has it too. I am pretty sure this is not a bug in the debugger, please ask on StackOverflow or Gitter if you need help

**Comment by rburtoff** [comment]
That would make sense.  I'm going to search out the PHP.ini files and see if I can find one that has the mysql and mysqli .DLLs commented out. I agree, I don't believe this is an issue with your plug-in, I think it's a PBKAC error. 

Thanks!

___________________________
Ray Burtoff
(856) 816-6117
burtoff@yahoo.com
