### ISSUE TITLE
[Question] Not showing Intellisense for Object function

### ISSUE THREAD

**Issue by benyaminl** [felixfbecker/vscode-php-debug#169]
PHP version:  7.1.5
XDebug version:  2.3.4?
Adapter version:  1.3.0 ? 

I've a PHP class name Db and it contains many function and init on the first include, I called the include file on other file, so it works well, but I wanted the php intellisense to show or peek the function that Db class have, and says no definition found. Is that a bug or not?
![image](https://user-images.githubusercontent.com/2817332/27217172-f0a82b9e-52a2-11e7-83d0-6fea29857b0d.png)

Because the other function that normal not object oriented are working well without problem even on different files. 
![image](https://user-images.githubusercontent.com/2817332/27217217-2ae85ca2-52a3-11e7-8874-19679ab71a8d.png)

Thanks before for look into this question.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#411
