### ISSUE TITLE
How to set up this plug in to the existing php solution to debug in visual studio code

### ISSUE THREAD

**Issue by chaluvadis** [felixfbecker/vscode-php-debug#17]
Hello I am a new to php, I am looking for a solution to debug php in visual studio code. I created launch.json to run the application but no luck. Any help appreciated. Thanks in advance.

**Comment by felixfbecker** [comment]
Did you install XDebug?

**Comment by chaluvadis** [comment]
Yes I have installed Xdebug..When I was debugging I am getting the following error.
request 'attach': Attach requests are not supported.

**Comment by felixfbecker** [comment]
That is weird... Attach requests are indeed not supported, but I can see from your screenshot that you have a launch configuration...

**Comment by chaluvadis** [comment]
I am also not understand the problem...  Do you have any idea how to debug this problem?

**Comment by felixfbecker** [comment]
Do you have the newest version of everything? Please try to set `"log": true` in your launch.json

**Comment by chaluvadis** [comment]
Latest Version means,  I am using php version 5.6, and XDebug is **php_xdebug-2.4.**, Visual Studio is also a latest version.

**Comment by felixfbecker** [comment]
the log gets printed to the debug console. I also just pushed a new release with some refactoring, maybe it magically fixes your problem?
