### ISSUE TITLE
cannot trace script with php-debug

### ISSUE THREAD

**Issue by egoriy33** [felixfbecker/vscode-php-debug#178]
PHP version:  5.5.9
XDebug version:  
Adapter version:  1.11.1

Your launch.json:  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
XDebug php.ini config:  

zend_extension = "Z:\usr\local\php5\ext\php_xdebug-2.5.4-5.5-vc11.dll"
xdebug.remote_enable=1
;xdebug.remote_host=127.0.0.1
;xdebug.remote_connect_back=1    # Not safe for production servers
;xdebug.remote_port=9000
;xdebug.remote_handler=dbgp
;xdebug.remote_mode=req
xdebug.remote_autostart=1
xdebug.remote_log = "http://localhost/tk/debug_log.txt"
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```
<?
print "step1";
print "step2";
print "step3"; // break point is here
print "step4";
?
step over, step into and step out buttons are inactive and not clickable.
Please help!

**Comment by josecanhelp** [comment]
I assume the buttons were not clickable because the script was not run. Even though you start the debugging listener, you will need to run the script with `php stepscript.php`.

**Comment by felixfbecker** [comment]
There is nothing I can do from the information provided.
