### ISSUE TITLE
Can't get PHP Extension to start in VSCode

### ISSUE THREAD

**Issue by momurray** [felixfbecker/vscode-php-debug#18]
Hi,
I've installed XDebug. I'm able to connect with other IDE clients. 
I've installed the php-debug extension using F1 then install extensions. The "installed extensions" show that I have it installed. 

When I go to debug window from within VC I can't see any PHP extension to choose to start debugging. All I can see is "Launch extension" but no way of selecting anything. 

Any ideas ? 

Mark

**Comment by felixfbecker** [comment]
You probably already had a launch.json. Either open your launch.json and edit the parameters (set `type` to `php` and `request` to `launch`) or delete it and create a new one by clicking the ⚙ icon and selecting "php"

**Comment by momurray** [comment]
Thank you. Deleting the existing .json worked perfectly. 

Really like the hover over variable inspector too. 

Mark
