### ISSUE TITLE
better Launch.json instructions or examples

### ISSUE THREAD

**Issue by gnubyte** [felixfbecker/vscode-php-debug#183]
You have supported launch.json settings but can you post a fully loaded example launch.json? It is confusing to non-nodejs users trying to figure out what to throw in this json file, or at least myself.

Thank you.

**Comment by felixfbecker** [comment]
Check out https://github.com/felixfbecker/php-language-server/blob/master/.vscode/launch.json
When you create a new launch.json, it should be prefilled with some examples?

**Comment by gnubyte** [comment]
Thanks for the quick reply. I appreciate your work so far but feel rather lost on the implementation of this in a work environment.

I think my problem is linking this debugger locally to a remote host that is listening with Xdebug. Most of the Youtube and external sites use a regurgitation of the text on your readme.  For example I know that I need a `serverSourceRoot`, however do I add a whole block like this to the launch.json?

`,
        {

            "name": "serverSourceRoot",

            "type": "php",

            "request": "launch",

            "program": "${file}",

            "cwd": "${serverSourceRoot}",

            "port": 9000

        }
`

If I am debugging remotely, it is fairly obvious that I am going to need to FTP the php files to the site or if windows send via SMB. There is nothing in this xdebug plugin that seems to signify that it is going to make this transfer. Do I stack this extension with others? How would I chain that together if xdebug plugin does not natively SFTP the files to the host?

**Comment by felixfbecker** [comment]
That doesn't look correct. I recommend you read up on launch.json in general: https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes
And then reread the documentation here: https://github.com/felixfbecker/vscode-php-debug#supported-launchjson-settings

`cwd` for example is clearly only for CLI contexts, which conflicts with debugging a remote server (you can't launch the app if you just attach).
All you need to change from the basic "Listen for XDebug" config to get it to work remote is add the two lines as described here: https://github.com/felixfbecker/vscode-php-debug#remote-host-debugging
No, there is no FTP/SFTP/SMB done by this plugin or VS Code in general. You are expected to have the same source code available locally, e.g. through a cloned git repo or through a FTP sync tool.
