### ISSUE TITLE
The maximum output of the debug console is 1024 characters

### ISSUE THREAD

**Issue by tiansin** [felixfbecker/vscode-php-debug#186]
PHP version:  7.18
XDebug version:  2.54
Adapter version:  

Your launch.json:  {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
XDebug php.ini config:  

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php

```
Thank you first!
The maximum output of the debug console is 1024 characters?
What is the maximum number of variable structures to show? Is there a way to show it completely?

![1](https://user-images.githubusercontent.com/4232281/29280203-e297dda0-814c-11e7-81ab-aeb36d958196.jpg)
The actual display only 32, originally the 60

**Comment by felixfbecker** [comment]
Please read the documentation: https://github.com/felixfbecker/vscode-php-debug#supported-launchjson-settings

**Comment by tiansin** [comment]
Thank you for your answer.

**Comment by pycr** [comment]
max_data

**Comment by C1b3r** [comment]
![image](https://user-images.githubusercontent.com/16479260/188647972-894b65fa-94d1-48e6-91a6-b4559ade2212.png)
if someone finds this, as a summary, put the xdebugSettings parameter with the field "max_data": -1.
