### ISSUE TITLE
Long variable  max_data is 1024 ! Please help

### ISSUE THREAD

**Issue by Postgre** [felixfbecker/vscode-php-debug#187]
PHP version:  7.1.9
XDebug version:  2.5.5
Adapter version:  

Your launch.json:  
XDebug php.ini config:  

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

Code snippet to reproduce:  
$maVariable = str_repeat('#', 8048). "<br/>"; 
					
	//echo ($maVariable);
	
	$maVariableSize = strlen($maVariable);
	
	echo ('La taille de cette variable est : ' . $maVariableSize);

**Comment by felixfbecker** [comment]
Please explain the issue.

**Comment by Postgre** [comment]
Hi,
Thanks for your feedback !
Please see the link https://github.com/felixfbecker/vscode-php-debug/issues/36
When debugging long size variable, the var inspection only shows first 1024 chars

PHP version: 7.1.9
XDebug version: 2.5.5

Thanks

**Comment by felixfbecker** [comment]
Set `xdebugSettings` as described in the docs https://github.com/felixfbecker/vscode-php-debug#supported-launchjson-settings

**Comment by Postgre** [comment]
Good, thank you very much !
