### ISSUE TITLE
Breakpoint does not stop ... (solved)

### ISSUE THREAD

**Issue by averonis** [felixfbecker/vscode-php-debug#188]
PHP version:  5.6.30
XDebug version:  2.2.5.1
Adapter version:  1.15.1

launch.json:
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "log": true            
        },
        {
            "name": "Remote XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "stopOnEntry": true,
            "serverSourceRoot": "/var/www/html/tst/",
            "localSourceRoot": "/var/www/html/tst/",
            "log": true
        } 

  
XDebug php.ini config:  

[XDebug]
zend_extension = /usr/lib/php5/20131226/xdebug.so
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_port=9000
xdebug.remote_host=127.0.0.1
xdebug.remote_log=/tmp/xdebug.log
xdebug.remote_handler=dbgp
xdebug.idekey="vscode"
xdebug.remote_connect_back = 1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  

Log opened at 2017-09-13 07:22:29
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 127.0.0.1:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/html/tst/debug.php" language="PHP" xdebug:language_version="5.6.30-0+deb8u1" protocol_version="1.0" appid="32635" idekey="vscode"><engine version="2.5.5"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2017 by Derick Rethans]]></copyright></init>

<- breakpoint_list -i 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="1"></response>

<- breakpoint_set -i 2 -t line -f file:///var/www/html/tst/debug.php -n 5
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" id="326350005"></response>

<- breakpoint_list -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="3"><breakpoint type="line" filename="file:///var/www/html/tst/debug.php" lineno="5" state="enabled" hit_count="0" hit_value="0" id="326350005"></breakpoint></response>

<- breakpoint_list -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="4"><breakpoint type="line" filename="file:///var/www/html/tst/debug.php" lineno="5" state="enabled" hit_count="0" hit_value="0" id="326350005"></breakpoint></response>

<- breakpoint_set -i 5 -t exception -x *
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="5" id="326350006"></response>

<- step_into -i 6
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="step_into" transaction_id="6" status="stopping" reason="ok"></response>

<- stop -i 7
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="7" status="stopped" reason="ok"></response>

Log closed at 2017-09-13 07:22:29

Adapter logfile (from setting `"log": true` in launch.json):  
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }

new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 3 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (10:22:29 AM)' } ] } }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments: 
   { source: { path: '/var/www/html/tst/debug.php', name: 'debug.php' },
     lines: [ 5 ],
     breakpoints: [ { line: 5 } ],
     sourceModified: false },
  type: 'request',
  seq: 4 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 5 } ] } }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 5 }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  type: 'request',
  seq: 6 }

<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'setExceptionBreakpoints',
  success: true }

-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 7 }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 8 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (10:22:29 AM)' } ] } }

<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 7,
  command: 'configurationDone',
  success: true }

<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'exited', threadId: 1 } }

Code snippet to reproduce:  
<?php
$a = 10;
$b =20;    <-break point there
echo $a*$b;
?>

hi,
when i start debug with "Launch currently open script", all is done.
But i want to run file from browser, and debug ...
start debugging with  "Remote XDebug"
and try to load url http://127.0.0.1/tst/debug.php?XDEBUG_SESSION_START=vscode in browser
scripts run and finish, but id vsc debug didn't stop and can't debug step by step.

im try and other configuration on launch.json:
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "log": true,
            "port": 9000
        }

but result is same .

p.s.
when start from console "debugclient" and try to load same url, browser wait 
and can send command from command line to debuger ...

**Comment by averonis** [comment]
SOLVED.
found zend debuger conf file in  /etc/php5/apache2/conf.d .
coment all rows, and debuging run in VSC ...

**Comment by LeReveur711** [comment]
Hello !
It seems that I have the same problem ... Everything seems to work properly except that it does not stop on break points ...

I looked for the file that you designate but I do not have it in my  /etc/php5/apache2/conf.d folder
/etc/php5/apache2/conf.d/:
05-opcache.ini    20-curl.ini       20-json.ini       20-memcached.ini  20-mysqli.ini     20-readline.ini
10-pdo.ini        20-gd.ini         20-mcrypt.ini     20-mysql.ini      20-pdo_mysql.ini  20-xdebug.ini

Any idea ? Thx for help

**Comment by averonis** [comment]
hi,
look in all apache directories for zend files. an in all conf files  ...
did you install zend debuger?

2017-10-19 16:39 GMT+03:00 Le Texier <notifications@github.com>:
