### ISSUE TITLE
Help with the configuration using docker

### ISSUE THREAD

**Issue by alissonschneiderr** [felixfbecker/vscode-php-debug#189]
> PHP version:  7.0
> XDebug version:  2.5.0
> Adapter version:  Visual Studio Code 1.13.0
> 
> Your launch.json: 
> 
> {
> 	"version": "0.2.0",
> 	"configurations": [
> 		{
> 			"name": "Listen for XDebug",
> 			"type": "php",
> 			"request": "launch",
> 			"port": 9000,
> 			"stopOnEntry": true,
> 			"localSourceRoot": "/home/alisson/projetos/g-mus-dev",
> 			"serverSourceRoot": "/home/developer/workdir"
> 		},
> 		{
> 			"name": "Launch currently open script",
> 			"type": "php",
> 			"request": "launch",
> 			"program": "${file}",
> 			"cwd": "${fileDirname}",
> 			"port": 9000
> 		}
> 	]
> }
>  
> XDebug php.ini config:  
> 
> zend_extension=xdebug.so
> xdebug.remote_enable=on
> xdebug.remote_handler=dbgp
> xdebug.remote_host=172.17.0.1
> xdebug.remote_port=9000

I'm trying to debug and it's not working, it works perfectly on netbeans

**Comment by felixfbecker** [comment]
Please ask support questions on StackOverflow or Gitter.
