### ISSUE TITLE
Debugger loses connection

### ISSUE THREAD

**Issue by imperez** [felixfbecker/vscode-php-debug#19]
Whenever I try to debug I quickly lose connection after multiple Requests. So for instance I see Request 2 & 3 listed and then the connection is dropped. I'm not sure if there's any other info I can give you to help out but let me know what you need.

**Comment by felixfbecker** [comment]
Please tell me which version of this extension, VS Code, PHP and XDebug you are on.
Then please set `"log": true` in your launch.json and post the output here, aswell as set `xdebug.remote_log` to some logfile and also post the result.

Multiple connections is a buggy feature and I would love to find out what's causing this.

**Comment by imperez** [comment]
I'm using Extension 1.3.2, PHP 5.5.32 and XDebug 2.3.3. I've attached the xdebug and debug log file.

[debug-log.txt](https://github.com/felixfbecker/vscode-php-debug/files/143328/debug-log.txt)
[xdebug.txt](https://github.com/felixfbecker/vscode-php-debug/files/143329/xdebug.txt)

**Comment by felixfbecker** [comment]
Sorry, I cannot figure out the problem from the logs.
Please try to update the extension and XDebug

**Comment by imperez** [comment]
I just upgraded the extension and things seem to be more stable so far. I lost connection once but not during another instance where I saw multiple requests. I'll keep an eye on it to see if I can bring back any other information.
