### ISSUE TITLE
Version 1.12.0 seems to have broken Debugging

### ISSUE THREAD

**Issue by mwidmann** [felixfbecker/vscode-php-debug#203]
I've been debugging in VSCode this morning, but since launch break the Debugger doesn't work anymore. Doesn't matter if I try to debug using the local php installation (7.1.1) or a remote one inside a Docker container, starting the debugger throws a "Debug adapter process has terminated unexpectedly". 

<img width="1438" alt="screen shot 2017-11-21 at 15 03 31" src="https://user-images.githubusercontent.com/251322/33076499-2a4f9d18-cecd-11e7-8a99-46ca0dc2195f.png">

There's no information in any of the output channels or the debug console. The error on the Console does not give any further information either.

<img width="1660" alt="screen shot 2017-11-21 at 15 03 17" src="https://user-images.githubusercontent.com/251322/33076478-204e70f0-cecd-11e7-884b-67fbefd57cbf.png">

my launch.json has not yet been updated to the newest Code workspace settings, but as I said, it worked this morning.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Local auf Port 9001",
      "type": "php",
      "request": "launch",
      "port": 9001,
      "log": false
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    },
    {
      "name": "Listen for XDebug in Docker Webserver Container (OVB)",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "serverSourceRoot": "/var/www/wordpress-custom/ovb/wp-content",
      "localSourceRoot": "${workspaceFolder}/wp-content",
      "log": false
    },
    {
      "name": "Listen for XDebug in Docker Webserver Container (VN,...)",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "serverSourceRoot": "/var/www/wordpress-custom/webpapers/wp-content",
      "localSourceRoot": "${workspaceRoot}/wordpress-custom/wp-content",
      "log": false
    },
    {
      "name": "Listen for XDebug in Importer Docker Container (OVB)",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "serverSourceRoot": "/opt/app-root/src/wordpress-custom/ovb/wp-content",
      "localSourceRoot": "${workspaceRoot}/wp-content",
      "log": false
    },
    {
      "name": "PHPUnit",
      "type": "php",
      "request": "launch",
      "port": 9001,
      "program": "/usr/local/bin/phpunit",
      "cwd": "${workspaceRoot}",
      "args": ["${file}", "-c", "${fileDirname}/../../phpunit.xml"]
    }
  ]
}
```

Using Code 1.18.1 on macOS 10.12.6 Sierra

**Comment by djgreg13** [comment]
Same issue here

**Comment by koperkiewicz** [comment]
Same here

**Comment by Qocotzxin** [comment]
Same issue here

**Comment by vitorsemeano** [comment]
The same is happening here. Early this morning it was working, then after the recent update, it does not work, even after a restart of the system.

**Comment by piqoni** [comment]
Same Issue

**Comment by Zeph33** [comment]
Same Issue :(

**Comment by mwidmann** [comment]
@stereoit posted the following workaround

> from this page https://github.com/felixfbecker/vscode-php-debug/releases/tag/v1.11.1 download the 1.11.1, uninstall the 1.12 extension from VCSode, disable extension autoupdate `"extensions.autoUpdate": false,"` open extension panel, install from VSIX, locate the 1.11.1.vsicx file, install

**Comment by Zeph33** [comment]
Only `node_modules` and `image` folders in v1.12.0 
no source, no folder `out`

**Comment by dschniepp** [comment]
__How to install from vsix__ https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by Qocotzxin** [comment]
@mwidmann solutions works great. Hope they fix the issue with 1.12

**Comment by Zeph33** [comment]
maybe this change ... replace `compile` by `build ` in  [package.json](https://github.com/felixfbecker/vscode-php-debug/blob/master/package.json)
[https://github.com/felixfbecker/vscode-php-debug/commit/a8e61435b07cca6aecd9ea88f2cee9a176321695#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](https://github.com/felixfbecker/vscode-php-debug/commit/a8e61435b07cca6aecd9ea88f2cee9a176321695#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by mrbianchi** [comment]
same error, hours wasted trying fixed it

**Comment by anibalsanchez** [comment]
Confirmed.

I have disabled "extensions.autoUpdate", uninstalled 1.12, installed https://github.com/felixfbecker/vscode-php-debug/releases/download/v1.11.1/php-debug-1.11.1.vsix from the Extension Manager and it works again.

**Comment by efcribeiro** [comment]
Same

**Comment by jmperro** [comment]
Please revert the update v1.12 and put again the v1.11.1

**Comment by lmarcelocc** [comment]
Same here. Reverting to 1.11 works fine.

**Comment by YLivay** [comment]
Works in 1.12.1 - thanks for the quick fix :D

**Comment by felixfbecker** [comment]
I apologise for the inconvenience. I automated the release process yesterday night but forgot the build step in the release stage.

**Comment by felixfbecker** [comment]
Also just added automatic uploads of vsix files as part of the release process. Seems to have helped a lot of folks today keep working despite the technical difficulties :)

**Comment by djgreg13** [comment]
Thanks you very much for quick fix

**Comment by efcribeiro** [comment]
Thanks Felix! It’s perfect.

**Comment by troyporter** [comment]
Yeah definitely an issue with 1.12.  Installed 1.11 and issue was resolved. instantly.

Debian Jessie
