### ISSUE TITLE
setFunctionBreakpoints support?

### ISSUE THREAD

**Issue by tsu1980** [felixfbecker/vscode-php-debug#21]
Hi, I updated VSCode version to 0.10.10 today. And I faced below error when start PHP debug(Listen for XDebug). 

Is this mean 'vscode-php-debug' does not support 'setFunctionBreakpoints' yet? 
Should i downgrade VSCode to the previous version?

```
-> setFunctionBreakpointsRequest
{ type: 'request',
  seq: 23,
  command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] } }
<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 23,
  command: 'setFunctionBreakpoints',
  success: false,
  message: 'request \'setFunctionBreakpoints\': unrecognized request',
  body: 
   { error: 
      { id: 1014,
        format: 'request \'setFunctionBreakpoints\': unrecognized request',
        sendTelemetry: true } } }
```

VSCode 0.10.10
PHP Debug: 1.4.0

**Comment by felixfbecker** [comment]
function breakpoints are not supported yet, but your error should not happen, because I am not sending `supportsFunctionBreakpoints`....

**Comment by qc1984326** [comment]
I was such a mistake,but my breakpoint is not in function。
`<?php

$a = '123';

echo $a;

?>`

`<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'setFunctionBreakpoints',
  success: false,
  message: 'request \'setFunctionBreakpoints\': unrecognized request',
  body: 
   { error: 
      { id: 1014,
        format: 'request \'setFunctionBreakpoints\': unrecognized request',
        sendTelemetry: true } } }`

VSCode 0.10.10
PHP Debug: 1.4.0

**Comment by felixfbecker** [comment]
Please let me know if 1.5.0 fixes your problems

**Comment by arjandepooter** [comment]
Ran into this an hour ago. 1.50 fixed it for me :+1:

**Comment by tsu1980** [comment]
Works fine. Thanks!
