### ISSUE TITLE
Feb Release Causes Debugging to Fail

### ISSUE THREAD

**Issue by clazette** [felixfbecker/vscode-php-debug#22]
It appears that the latest release of VS Code (February) has caused PHP debugging to stop working. Are others experiencing any issues?

Thanks,
Chad

**Comment by felixfbecker** [comment]
@clazette Are you on the newest version (1.5.1)?

**Comment by clazette** [comment]
How do I verify the extension version?

**Comment by clazette** [comment]
No, I am not on the latest version. I am on 1.1.2. So, that could explain it.

**Comment by clazette** [comment]
Updating to the latest version solved the issue. Thank you very much, Felix!

**Comment by felixfbecker** [comment]
No problem, Feb release had a bug in it that broke the adapter and I just got around fixing it a few hours ago ;)

**Comment by clazette** [comment]
Excellent. Thank you for getting the issue resolved. I'm sure you were just waiting around for VS Code to be released so that you could address their bug :)
