### ISSUE TITLE
Correct settings to XDebug in VSCode and Lando (drupal 8 recipe) 

### ISSUE THREAD

**Issue by MatthieuScarset** [felixfbecker/vscode-php-debug#222]
Hi @felixfbecker, and thank you for this great extension!

I thought I would share my settings for those who are trying to use PHP Debug with a [Lando dev environment](https://docs.devwithlando.io/tutorials/drupal8.html).  I hope that it will save time for others :smile: 

Basically, you need to add a custom `php.ini` file so that XDebug get started remotely and automatically.

```
# Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1 
xdebug.remote_autostart = 1 
```

Then, you tell `Lando` to use this custom file:
https://gist.github.com/MatthieuScarset/0c3860def9ff1f0b84e32f618c740655#file-lando-yml

Finally, you need to set the custom `pathMappings` variable in `launch.json`:
https://gist.github.com/MatthieuScarset/0c3860def9ff1f0b84e32f618c740655#file-launch-json

That's it!

**Comment by felixfbecker** [comment]
Thanks! I would recommend though to post this as a Q&A on StackOverflow, as this is not really the right place for this.

**Comment by tsega** [comment]
@MatthieuScarset I believe your gist is part of the official Lando docs now; https://docs.devwithlando.io/tutorials/lando-with-vscode.html

**Comment by MatthieuScarset** [comment]
It is @tsega Thanks for adding the link here for future reference.

**Comment by Aldo-f** [comment]
> @MatthieuScarset I believe your gist is part of the official Lando docs now; https://docs.devwithlando.io/tutorials/lando-with-vscode.html

&rarr; https://docs.lando.dev/guides/lando-with-vscode.html
