### ISSUE TITLE
Role of XDEBUG_SESSION cookie

### ISSUE THREAD

**Issue by papadi** [felixfbecker/vscode-php-debug#24]
I'm a bit confused with the role of this XDEBUG_SESSION cookie. It is not mentioned anywhere in the documentation of this plugin, but in my case, I managed to make it work only when this cookie is present and it has this specific value: 58027742. Now... why this value?
Before giving this plugin a shot, I was experimenting with PHP Tools for Visual Studio. And when I was launching my project using that one, it would open a browser with XDEBUG_SESSION_START=58027742 in the end. It is weird, but the only way I can have debugging with Visual Studio Code and vscode-php-debug plugin is to append this to my page url ?XDEBUG_SESSION_START=58027742
Any ideas?

**Comment by felixfbecker** [comment]
There are multiple ways to make XDebug start a debug session when you request a PHP file from your webserver, setting a GET or POST parameter, setting a cookie or using a browser extension that sets these. Another solution which I find the easiest is to set `xdebug.remote_autostart` in php.ine, which will make XDebug always try to start a session. This is the way I recommend in the readme. But you can of course use the other ways too. The number is simply an ID for the session, it doesn't mean anything, you just have to use the same value everywhere.

You can read more here: https://xdebug.org/docs/remote#browser_session

**Comment by papadi** [comment]
Unfortunately the remote_autostart doesn't work for me. I think I forgot to
mention that I'm doing remote debugging. The app is in a vagrant VM. So you
are saying that the ID value is not important as long as it is the same
everywhere. But where is this everywhere? The only place I have it know is
a cookie, but it somehow works. If I change the value to something else it
doesn't.

**Comment by felixfbecker** [comment]
For remote host debugging, a bit more setup is necessary. You will either have to set `remote_host` to the IP of the machine you are running VS Code on or set `remote_connect_back = 1`. Please refer to the XDebug documentation I linked, I don't know anything more than what it says on that page ;)
