### ISSUE TITLE
Poorly formatted php does not hit set breakpoints

### ISSUE THREAD

**Issue by weinand** [felixfbecker/vscode-php-debug#25]
_From @vsccarl on March 11, 2016 19:41_

OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

When debugging php with XDebug, if the code is not correctly formatted a breakpoint will not hit.
Example:
![phpbreakpointpoorformat](https://cloud.githubusercontent.com/assets/12900364/13713473/fb0090cc-e77d-11e5-992b-deb4d17fbca4.JPG)

_Copied from original issue: Microsoft/vscode#4033_

**Comment by felixfbecker** [comment]
It seems like this is not related to poorly formatted code, but to multi line expressions in general. The breakpoint gets set correctly, but XDebug doesn't stop. It only works if you change it to a single line expression or set the breakpoint in the seconds line (or somewhere in the middle of the array):
![image](https://cloud.githubusercontent.com/assets/10532611/13738237/b2f682ee-e9c3-11e5-8f20-ff4ada0ed069.png)

**Comment by felixfbecker** [comment]
PHP Tools for Visual Studio behave the same here:
![image](https://cloud.githubusercontent.com/assets/10532611/13738567/338286ea-e9c6-11e5-8c7c-1d1b5a3e9ba3.png)
