### ISSUE TITLE
Variable gets truncated

### ISSUE THREAD

**Issue by PipCodeBoy** [felixfbecker/vscode-php-debug#260]
Why do variables get truncated and not show the full value? Is there any way to change this to show the full variable value?

![image](https://user-images.githubusercontent.com/17992048/38864662-afb49eb8-423b-11e8-9bc5-3b7127b319bd.png)

**Comment by felixfbecker** [comment]
Please refer to the XDebug documentation, the adapter doesn't truncate it, it's XDebug. You can customize XDebug settings through launch.json. They get truncated because else big variables can easily slow down the debugger.

**Comment by PipCodeBoy** [comment]
And where do I find the parameter to add to launch.json that fixes that?? Thanks

**Comment by skippednote** [comment]
@PipCodeBoy 

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "pathMappings": {
        "/app/": "${workspaceRoot}"
      },
      "xdebugSettings": {
        "max_data": -1,
        "max_children": -1
      }
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}

```

**Comment by ww9** [comment]
@skippednote That worked but now VSCode is having a hard time displaying 132 attributes 😑

![image](https://user-images.githubusercontent.com/27555162/75879030-fe683d80-5df0-11ea-9877-ad405973c418.png)

**Comment by ccjjmartin** [comment]
Same with strings, while I can now copy and paste the value in full with the new settings (thank you for that example by the way).  I cannot actually see the data within vscode.

**Comment by romeof1980** [comment]
I had a similar issue with xdebug 3 and vscode 1.66.2 on Ubuntu 20.04.4 (and vscode ext "PHP Debug" 1.26.1).
@skippednote pointed me on the right solution.
just replace "-1" (does not work, completely truncate the variables) with a higher value (like 9999).
```
      "xdebugSettings": {
        "max_data": 9999,
        "max_children": 9999
      }
```
tested with 2 different config (listening for xebug and build in server) with the same result.
working with magento 2 we have some very big objects and this solves it nicely.
cheers!
