### ISSUE TITLE
Adapter doesn't show in call stack on atart and restart

### ISSUE THREAD

**Issue by Spown** [felixfbecker/vscode-php-debug#262]
Adapter version:  1.12.3

![](https://drive.google.com/uc?id=18rvG7TlhsZrEtFjXhIdkgrETTgkF7K6M)

When starting or restarting PHP-Debug - the adapter doesn't  get shown in the call stack panel. Only when I change the stae of another adapter the true state is reflected. It is extremly annoying since I don't use the standard VSC floating debugger widget but [statusbar-debugger](/fabiospampinato/vscode-statusbar-debugger#demo) instead. it doesn't have it's own select and one can only switch between debuggers via call stack (which is difficult if the debugger is not there).  

launch.json: 
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://127.0.2.2/index.html",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "PHP XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true
        }
    ]
}
```
log:
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }

-> disconnectRequest
{ command: 'disconnect',
  arguments: { restart: true },
  type: 'request',
  seq: 3 }
```
Thank you.

**Comment by Spown** [comment]
>Could you please include your XDebug log?

With the repro steps above the log file remains empty. It only starts to fill after I run some php. BTW, after running the php file while the debugger is invisible - the debugger does appear in the call stack. 

Anyway here is the log (after repro steps and running a php file)
```
Log opened at 2018-04-20 04:38:31
I: Connecting to configured address/port: localhost:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///D:/Projects/regform/regform/submit.php" language="PHP" xdebug:language_version="7.2.3-dev" protocol_version="1.0" appid="13248" idekey="Spown"><engine version="2.6.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>

<- breakpoint_list -i 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="1"></response>

<- breakpoint_list -i 2
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="2"></response>

<- run -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="3" status="stopping" reason="ok"></response>

<- stop -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="4" status="stopped" reason="ok"></response>

Log closed at 2018-04-20 04:38:31
```

**Comment by felixfbecker** [comment]
Well that makes perfect sense. What call stack would you want it to show when no process has connected yet? There is one call stack entry shown for every process.
I would recommend you open an issue at the statusbar debugger extension or use the native UI.

**Comment by Spown** [comment]
But the debugger is running though, isn't it? I'm not complaining about call stack missing (php is not a runtime, so I don't expect it having one). But the debugger adapter should be shown as long as it is running/listening. Statusbar debugger extension has nothing to do with this.

**Comment by Spown** [comment]
![](https://drive.google.com/uc?id=1RwDNQaLiOtT_G3wGWxY1yWK6r8sGL--9)

**Comment by felixfbecker** [comment]
VS Code only shows the item for the debugger if there were callstacks reported for it.

**Comment by Spown** [comment]
this is not true. as you can see on the picture above your debugger is shown while not having any call stack (it is unfolded but empty). And as I said and shown in the OP changing the status of another debugger "conjures PHP Debugger from the void" even if it hasn't done anything yet.

Furthermore your debugger while running is always shown in the status bar (in this picture I've disabled the statusbar-debugger):
![](https://drive.google.com/uc?id=107fQwjYSILkxOzvd65qcusYyaB0uCiFr)
but it is missing from the Call Stack until some other debugger extension refreshes it and show's yours (or untill a php has been ran).

**Comment by felixfbecker** [comment]
What makes you believe that the adapter is doing something wrong here? Reading your logs, the debugger does all requests and responses correctly, so if you expect it to be shown in the UI but it isn't, I would assume that is a UI issue

**Comment by Spown** [comment]
> I would assume that is a UI issue

Maybe. I don't know - I'm not the one developing this extension and I know nothing about the VSC Debugger API. Maybe an upstream issue is in order here. So maybe you could look into it instead of inventing reasons not to?

I can report a bug to VSC, but I don't know whether I should. Right now I only see your extension "misbehaving" (I've been using Node, Chrome, Firefox, NWJS debuggers and your's is the first one doing this).

Or just say you don't want to. I mean it's open source and nobody owes anybody anything.

**Comment by Spown** [comment]
I would imagine that there is a refresh/redraw method/event that is being ran/triggered on call stack change that among other things exposes the debugger graphical element  in the call stack. Runtime debuggers probably trigger it automatically by the virtue of supplying a call stack from the very beginning. But on-demand debuggers should run them explicitly after init is done. That is if this method is exposed of course. If it's not then one should probably file an upstream issue to VSC. I can do it, but can you confirm that there is nothing you can do? Maybe the method was introduced after you've started development or you've just missed it?
