### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by acicovic** [felixfbecker/vscode-php-debug#263]
Hi,

As reported by @arby50 and @loppp in issue #149, this error started showing up. This was working before and there were no config changes, so I suspect that it has to do with VSCode's or the extension's update to their latest versions.

I am willing to help you debug this, but I don't know where to start. If there are any guidelines let me know.

Thanks!

**Comment by acicovic** [comment]
Going to the .vscode/extensions directory I saw two folders of vscode-php-debug and deleted both. I reinstalled the plugin and things seem to work OK so far. This might be a VSCode issue as I had the Vim plugin not working as well, and this got fixed with the same method.

**Comment by arby50** [comment]
Finally got a free minute (when not using the debugger) to try this.  I updated to the latest debugger version 1.12.3 and the latest VSCode 1.22.2 and am able to debug and am not able to duplicate the error/bug.  I assume it is therefore not, or is not any longer, an issue.  Thanks for the replies and investigation.
