### ISSUE TITLE
Confirm Debug Console does not interact with PHP?

### ISSUE THREAD

**Issue by nathanielks** [felixfbecker/vscode-php-debug#267]
Hi there!

I just wanted to confirm with you that the Debug Console does not interact with the live PHP request, and thus can't be used like a PHP REPL? PHP Storm has this ability and I just wanted to confirm it's not present in this extension. Thank you for putting this together, it's wonderful!

**Comment by nathanielks** [comment]
Hmm, I've got a session running and unfortunately it seems to break things. I'm stopped on a breakpoint and am trying to run `echo 'test'` and it errors:

```
echo 'test'
syntax error, unexpected 'echo' (T_ECHO), expecting ';'
```

Subsequently any other debugging actions are broken after this as well. I can't step or resume the request. I have to stop or reload the debugging session for step functions to work again.

---
PHP version:  7.2.4
XDebug version:  2.6.0
Adapter version:  1.12.3

Your launch.json:  
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "stopOnEntry": true,
            "pathMappings": {
                "/srv/www/example.com/current": "${workspaceRoot}"
            },
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
XDebug php.ini config: 
```
[XDebug]
zend_extension=xdebug.so

; Remote Debugging
xdebug.remote_enable=1
xdebug.remote_connect_back=1
xdebug.remote_autostart=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_log=/tmp/xdebug.log
xdebug.idekey=XDEBUG
xdebug.extended_info=1
xdebug.max_nesting_level=200

; Display Settings
xdebug.force_display_errors=0
xdebug.force_error_reporting=0
xdebug.scream=0
xdebug.var_display_max_children=128
xdebug.var_display_max_data=512
xdebug.var_display_max_depth=3

; Function/Stack Traces
xdebug.collect_assignments=0
xdebug.collect_includes=1
xdebug.collect_params=0
xdebug.collect_return=0
xdebug.collect_vars=0
xdebug.show_exception_trace=0
xdebug.show_local_vars=0
xdebug.show_mem_delta=0
xdebug.trace_enable_trigger=0
xdebug.trace_enable_trigger_value=
xdebug.trace_format=0
xdebug.trace_options=0
xdebug.trace_output_dir=/tmp
xdebug.trace_output_name=trace.%c

; Profiler
xdebug.profiler_append=0
xdebug.profiler_enable=0
xdebug.profiler_enable_trigger=0
xdebug.profiler_enable_trigger_value=
xdebug.profiler_output_dir=/tmp
xdebug.profiler_output_name=cachegrind.out.%p
```
(gist contains both)
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  https://gist.github.com/nathanielks/fe2ff0422e538c64134b3bb36ca63616
Adapter logfile (from setting `"log": true` in launch.json):  https://gist.github.com/nathanielks/ddb1fe69174c95e435e46f0717d81a15

Code snippet to reproduce:  
```php
<?php
phpinfo();
```

**Comment by felixfbecker** [comment]
And have you tried adding a semicolon? `echo 'test'` is not valid PHP, `echo 'test';` is though

**Comment by nathanielks** [comment]
Correct, it also doesn't work:
```
echo 'test';
syntax error, unexpected 'echo' (T_ECHO), expecting ';'
```

**Comment by nathanielks** [comment]
It sounds like there's a command being run before it that hasn't been terminated with a `;`?

**Comment by felixfbecker** [comment]
[According to your logs](https://gist.github.com/nathanielks/fe2ff0422e538c64134b3bb36ca63616#file-xdebug-log-L37) the adapter sends the right value to XDebug, so please file this on XDebug.

**Comment by derickr** [comment]
You don't send the right value, you send the value without trailing ; — see discussion at https://bugs.xdebug.org/view.php?id=1548

**Comment by nathanielks** [comment]
To clarify for posterity, I _was_ seeing a syntax error for both `echo 'test'` and `echo 'test';`. Today I am no longer seeing that error. I just tried reverting back to 1.22.2 and 1.22.0 to see if I could reproduced the error and I was unable to do so. I'm not entirely sure what the problem was, or why I'm not longer seeing it ¯\_(ツ)_/¯

**Comment by felixfbecker** [comment]
> PHPStorm automatically wraps function definitions and other operations in an eval statement behind the scenes. @felixfbecker I took a look at the issue tracker and I don't see this as a planned feature. Would there be any chance this could be implemented in the future? Should I open another ticket requesting that?

I don't get any value out of this extension myself anymore so to be honest there are zero planned features (as in, that I plan to work on). You can open that ticket, or you can let it be, if nobody submits a PR it will probably never become a reality.
