### ISSUE TITLE
Provide evaluateName to enable variables right click options

### ISSUE THREAD

**Issue by mfrsousa** [felixfbecker/vscode-php-debug#270]
On Debug Variables when debugging php file all right mouse button click options are disabled and cannot copy/set any values or add to  watches.

Please see issue on VsCode 
https://github.com/Microsoft/vscode/issues/49605

**Comment by lucasctd** [comment]
has anyone found any way to fix this?

**Comment by OscarBastardo** [comment]
I'm having the same issue

**Comment by jeffalperin** [comment]
I would also like this feature.

**Comment by Octet83** [comment]
+1 here

**Comment by felixfbecker** [comment]
This was fixed in #295
