### ISSUE TITLE
Fields of objects on debug

### ISSUE THREAD

**Issue by guitarhero1** [felixfbecker/vscode-php-debug#271]
PHP version:  5.6.25
XDebug version:  php_xdebug-2.4.1-5.6-vc11

My launch.json:  
{
 "name": "Listen for XDebug",
"type": "php",
"request": "launch",
 "port": 9000,
 "max_children": 5,
 "max_depth": 6
}  

XDebug php.ini config: 
zend_extension=php_xdebug-2.4.1-5.6-vc11.dll
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.profiler_enable=0
xdebug.profiler_output_dir=/Windows/Temp
xdebug.trace_output_dir=/Windows/Temp

xdebug.profiler_enable_trigger="1"
xdebug.auto_trace="0"
xdebug.collect_includes="1"
xdebug.collect_params="4"
xdebug.collect_return="1"
xdebug.collect_vars="1"
xdebug.default_enable="1"
xdebug.dump_once = On
xdebug.dump_globals = On
xdebug.dump_undefined = On
xdebug.dump.SERVER = REQUEST_METHOD,REQUEST_URI,HTTP_USER_AGENT
xdebug.dump.REQUEST=*
xdebug.show_exception_trace = Off
xdebug.show_local_vars = 1
xdebug.var_display_max_depth = 6
xdebug.trace_output_name = trace.%c.%p
xdebug.extended_info=1
xdebug.var_display_max_depth = 50
xdebug.var_display_max_children = 256  

When I debug, I see only 32 fields of object or elements of array in vars window. I can't find setting in settings files and Internet or it actually doesn't exist?  
There is photo: https://stackoverflow.com/questions/50154471/parameters-in-debug-inspector

**Comment by guitarhero1488** [comment]
Very important...

**Comment by SidIcarus** [comment]
Add this to your `launch.json`: `"xdebugSettings": {"max_data": -1, "max_children":-1}`

Note: This is documented in the `README`.
