### ISSUE TITLE
Cannot connect to remote debugging session.

### ISSUE THREAD

**Issue by MakotoE** [felixfbecker/vscode-php-debug#272]
PHP version:  5.6.36
XDebug version:   2.5.5
Adapter version:  1.12.3

Your launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,

            "pathMappings": {
                "/home/site/wwwroot/": "${workspaceRoot}",
            },
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

XDebug php.ini config:
```
zend_extension="D:\home\site\wwwroot\bin\php_xdebug-2.5.5-5.6-vc11-nts.dll"

[XDebug]
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_host="00.00.00.000" ; (my ip address)
xdebug.remote_log="log.txt"
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  <strike>It's empty.</strike>

Edit: I was wrong - it says:
Log opened at 2018-06-03 16:59:07
I: Connecting to configured address/port: 00.00.00.000:9000.
E: Time-out connecting to client. :-(
Log closed at 2018-06-03 16:59:08

Adapter logfile (from setting `"log": true` in launch.json):  
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
-> disconnectRequest
{ command: 'disconnect',
  arguments: { restart: false },
  type: 'request',
  seq: 3 }
<- disconnectResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'disconnect',
  success: true }
```

The web server does not stop at any of my breakpoints, when I run "Listen for XDebug" and I go to my site in my browser. Both the server's files and my files are identical, just in different path locations. I can tell that the correct settings are loaded to Xdebug by checking the `phpinfo()` and seeing that all four settings from the ini are loaded. I have double checked that the IP address and port are matching between mine, the launch.json, and the server's Xdebug settings. I have tried disabling my firewall.

Is there anything else I should be checking, to allow me to remote debug the server?

**Comment by halllo** [comment]
I am having the same problem.

**Comment by MakotoE** [comment]
@halllo You might want to open a new issue describing your situation. I closed this one because it wasn't a big deal that I couldn't remote debug. I mostly debugged locally, and used a log if I needed to do it remotely.
