### ISSUE TITLE
Handle special characters correctly

### ISSUE THREAD

**Issue by Dexxes** [felixfbecker/vscode-php-debug#276]
Hi,

I discovered that #117 did not fix errors with special characters entirely. I am refering to your answer [here](https://gitter.im/felixfbecker/vscode-php-debug?at=584e89ddf666c5a13800e269)
I had a Ü in a directory name and always got an "URI is malformed" exception, but when I renamed that directory the exception was gone.
Please make sure to handle **Üü Ää Öö ß** properly ;)

Thank you for your work ;)

**Comment by felixfbecker** [comment]
Do you have a stack trace?
Maybe you could create a failing test case?

**Comment by Dexxes** [comment]
This is the stack trace:

> -> stackTraceRequest
> { command: 'stackTrace',
>   arguments: { threadId: 1, startFrame: 0, levels: 20 },
>   type: 'request',
>   seq: 13 }
> <- stackTraceResponse
> Response {
>   seq: 0,
>   type: 'response',
>   request_seq: 13,
>   command: 'stackTrace',
>   success: false,
>   message: 'URI malformed',
>   body: { error: { id: 0, format: 'URI malformed', showUser: true } } }

The path of the project I debug is __C:\Users\jvb\VB Cloud\GRÜNE JUGEND\GRÜNE JUGEND Bundesverband\Meisterei des Netzes\webspace\wordpress\wp-content\plugins\gjmf__

I use IIS as a local webserver.

I hope this helps!
