### ISSUE TITLE
Unable to Copy/Set Variables within the debug Variables window

### ISSUE THREAD

**Issue by codehooligans** [felixfbecker/vscode-php-debug#278]
I've ask in other VSCode community site and all pointed to support within the debugger. As I'm using this PHP debugger it brought me here. My understanding is in other languages this works as expected. But for some reason in this PHP debugger when I right-click on a variables in the Variables' debug window I get the little popup showing options to Set Values, Copy Value, Copy Expression and Add to Watch but they are all greyed out and not functional. 

https://monosnap.com/file/1SQ78tzPQvlviGJ2pXFFxzvu1xjCry

Once I add items to the debug Watch window I can Copy, Set etc. But would really like to have this work under the Variables window .

My details:

Operating system: OS X 10.13.5
VSCode: 1.24.1
PHP Debugger: 1.12.3

launch.json file
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

**Comment by valVk** [comment]
Here is similar issue in another project
https://github.com/Microsoft/ptvsd/issues/559

**Comment by marcelloh** [comment]
I have this too and find it higly irritating. You have to add some var to the watch winbdow by hand and then you can copy it, and then I can remove it from the watch window again. Far too many steps.

**Comment by marcelloh** [comment]
ehm, and how do I use the github version?
(or: how long does it take for VSC to pick it up auto-magically?)

Btw:  a big THANK YOU for solving this

**Comment by codehooligans** [comment]
https://monosnap.com/direct/Gg9lTFm67iXJtF7Q6MEhRVoipsdmPH
So in VCCode go into the extensions listing. This is the square icon below the debug on the left most channel. Then within the extensions listing will be a '...' click that and select 'Check for Updates'.

**Comment by marcelloh** [comment]
YAY! Thans. This is good :-) works as expected. (time to clean up my enormous watchlist gheghe)
