### ISSUE TITLE
XDebug fails to connect because vscode-php-debug is listening on IPv6

### ISSUE THREAD

**Issue by mscharley** [felixfbecker/vscode-php-debug#288]
PHP version:  7.1.20
XDebug version:  2.6.0
Adapter version: 1.12.3

Your launch.json:  

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "pathMappings": {
        "/portal": "${workspaceFolder}",
      },
      "port": 9000,
      "log": true
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```

XDebug php.ini config:
```
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=1
xdebug.remote_log=/var/log/xdebug.log
xdebug.remote_host=host.docker.internal
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
```
Log opened at 2018-08-01 02:13:59
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 172.19.0.1:9000.
W: Creating socket for '172.19.0.1:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
Log closed at 2018-08-01 02:13:59
```

Adapter logfile (from setting `"log": true` in launch.json):
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
```

Code snippet to reproduce:
```php
<?php
phpinfo();
```

Also relevant:
```
$ lsof -nP -i4TCP:9000
COMMAND     PID            USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Code\x20H 46903 matthewscharley   28u  IPv6 0x32d841ebd93c8e67      0t0  TCP *:9000 (LISTEN)
```

It would be great to be able to specify a bind address, which would then let me solve this easily. Alternatively, binding to both IPv4 and IPv6 would be an even better solution.

**Comment by mscharley** [comment]
Also relevant, the top of my hosts file:

```
$ head /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```

That should mean that the IPv4 address should be preferred, but it's not working for this project for some reason.

**Comment by mscharley** [comment]
I've seen #162 and according to the docs the advice given there is wrong: https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback

```
If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
```

This means that it's actually impossible to specifically setup an IPv4 address to listen on currently. Again, allowing a bind address would solve this problem. Not sure how hard this would be to add but looks like it shouldn't be too hard from the code - just need to add a hostname here from an argument, the same as the port currently is.

https://github.com/felixfbecker/vscode-php-debug/blob/master/src/phpDebug.ts#L313

**Comment by mrzarkovic** [comment]
+1

**Comment by HeikoAdams** [comment]
Any progress on this issue?

**Comment by mscharley** [comment]
The PR I put up still merges cleanly and worked for me when I was dealing with this issue, so this is with @felixfbecker

**Comment by mscharley** [comment]
For what it's worth, I ended up finding out this wasn't the actual issue on my Mac OS host after all, but it's been sufficiently long that I forget what the actual issue was now. This PR did work as intended though so I left it up.

**Comment by martin-schulze-vireso** [comment]
I hit the exact same problem with a dockerized XDebug. Since it was not possible to convince docker to do IPv6 networking I needed to patch up the VS Code side to listen on IPv4 addresses.
Seeing that the PR seems to be stuck: Is there anything I can to to facilitate a quick solution to the PR?
