### ISSUE TITLE
copy a var from debug or wacth windo does on ly copy a part (when it is a bit bigger)

### ISSUE THREAD

**Issue by marcelloh** [felixfbecker/vscode-php-debug#297]
When I have a var that contains rendered html, I expect the result to be more than the number of bites I see now.
According to my xdebug, it should have a max of 2048 bytes, but it seems half in the plugin.
does the plugin takes this value as it's maximum string length?: if not, please make it configurable?

I hope below is enough info

PHP version:  7.2
XDebug version: 2.6.1  
Adapter version: ?

Your launch.json:  
{
    "php.executablePath": "c:/Development/Laragon_lite/bin/php/php-7.2.9-nts-Win32-VC15-x64/php.exe",
    "php.validate.executablePath": "c:/Development/Laragon_lite/bin/php/php-7.2.9-nts-Win32-VC15-x64/php.exe",
    "php.validate.run": "onType",
    "window.zoomLevel": 0,
    "editor.mouseWheelZoom": true,
    "window.menuBarVisibility": "default",
    "editor.minimap.enabled": false,
    "[php]": {
        "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
    },
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "breadcrumbs.enabled": true,
}

XDebug php.ini config:
zend_extension = "C:/Development/Laragon_lite/bin/php/php-7.2.9-nts-Win32-VC15-x64/ext/php_xdebug-2.6.1-7.2-vc15-nts-x86_64.dll"
xdebug.idekey = "Intellij"
xdebug.profiler_append = 0
xdebug.profiler_enable = 1
xdebug.profiler_enable_trigger = 1
xdebug.profiler_output_dir = "C:/Development/Laragon_lite/tmp/xdebug"
xdebug.profiler_output_name = "cachegrind.out.%u-%H_%R"
xdebug.remote_enable = 1
xdebug.remote_handler = "dbgp"
xdebug.remote_host = localhost
xdebug.remote_port = 9000
xdebug.var_display_max_depth = 20
xdebug.var_display_max_data = 2048
xdebug.trace_output_dir = "C:/Development/Laragon_lite/tmp/xdebug"
//xdebug.trace_enable_trigger=1
//xdebug.trace_output_name=xdebug.trace.%t.%R
//xdebug.show_mem_delta=1
//xdebug.collect_params=4
//xdebug.collect_return=1
xdebug.trace_format=1

**Comment by felixfbecker** [comment]
It might be because the byte limit is applied to base 64 encoded data, I'm not sure. In any case, the adapter just passes the settings to XDebug raw, it doesn't special case settings.
