### ISSUE TITLE
Add source code mapping

### ISSUE THREAD

**Issue by gianugo** [felixfbecker/vscode-php-debug#3]
Some projects don't have their PHP code in the root folder - a few debuggers out there have a source mapping setting that allows to map the server layout to a different folder. Would be great to have something like that here as well. 

Thank you for this extension - perfect timing as I used it right away and it worked like a charm!

**Comment by felixfbecker** [comment]
Thanks for the feedback. Btw, on what OS are you on? Because I haven't tested at Linux and OSX yet.
How do you imagine the feature? Some setting in launch.json that sets a "root" folder? Could you elaborate?

**Comment by gianugo** [comment]
I'm on an El Cap Mac and it works just fine. To mimic what I have seen in other debuggers you may need two settings in launch.json - say local_source_path and an optional remote_source_path. Two cases I have in mind:

1. The local source is in src/ and it gets published to http://hostname/blog/ You would have something like ` "local_source_path": "./src/", "remote_source_path: "/blog/"`
2. The local source is in src/ and it gets published to the root. You may have ` "local_source_path": "./src/", "remote_source_path: "/"` or just omit `remote_source_path` in which case it defaults to `"/"`

Makes sense?

**Comment by felixfbecker** [comment]
I don't think I understand completely what you mean. Some background: XDebug **always** sends absolute file URIs. So if I set up my webserver to serve `C:\users\felix\myproject\src` under `http://localhost/blog`, XDebug would respond with `file://c/users/felix/myproject/src/index.php` in the stack trace, which the adapter converts to `C:\users\felix\myproject\src\index.php` for VS Code.

Are you talking about remote debugging a webserver on a different host, like the production server?

**Comment by gianugo** [comment]
Yes, sorry, I should have mentioned that I'm using your extension for remote debugging. The good news is that it works fine. :)

**Comment by felixfbecker** [comment]
Yeah sure it's always remote debugging, we are always talking over a TCP socket with XDebug. The question is just if it's on a different host. Because I don't know what XDebug would report as file URIs in that case, but my guess is it would just report the file paths on the server. And in that case of course some sort of path mapping is needed.

To be honest though, the development environment (in a git workflow) is always local, so this is not a problem. In production XDebug should never run because of performance. So the only environment I can think of where this is needed is a staging environment on the server. Is this your use case?

If yes, I would think that there needs to be a `serverSourceRoot` setting (like `/srv/www`), that gets _stripped_ from the paths, and _replaced_ by the value of `localSourceRoot` (like `c:\users\felix\myproject\src`). If my assumption that XDebug just reports local server paths is true.

**Comment by gianugo** [comment]
Yes, my use case is about staging servers (I was able to pinpoint an issue where my local Apache configuration was not reflected precisely in the remote's IIS conf). I can probably try and tap the wire to see what the `fileuri` attribute looks like in the XDebug stuff I'm getting back from my staging server - your assumption makes a lot of sense.

**Comment by gianugo** [comment]
And here is what I'm getting - indeed a local path:
`fileuri="file:///D:/home/site/wwwroot/wp-admin/admin.php"`

**Comment by felixfbecker** [comment]
@gianugo I implemented a prototype on the `sourcemap` branch. It would be nice if you could try it and tell me if it works because I don't have a setup for this.

**Comment by gianugo** [comment]
@felixfbecker I'm afraid I didn't manage to see it working. I tried attaching a debugger but I'm running into other weird issues (for some reason I'm getting an exception on line 42 of `dbgp.ts` - this happens only during debugging). Will keep looking into it.

**Comment by gianugo** [comment]
Made some progress and I was able to debug (the issue was an old version of node still lingering around). The replace on line 207 of `phpDebug.ts` doesn't seem to work - I will try to fix it tomorrow tomorrow if you don't beat me to it.

**Comment by felixfbecker** [comment]
I don't have time today and also don't have a remote debugging setup so your help is appreciated. But I think in general the concept should work (I build a regexp that matches the beginning of the line).

**Comment by gianugo** [comment]
I can confirm it does work and the mistake was on my side. I forgot that this being JSON, Windows paths will need to be escaped so my D:\home\site\wwwroot (default for Azure Web Sites) didn't quite work. Using either forward slashed (D:/home/site/wwwroot) or escaped backslashes (D:\\home\\site\\wwwroot) worked just fine. I'd love to see this change merged. Thanks!

**Comment by felixfbecker** [comment]
Good point, I will call `path.normalize()` on the settings so one launch.json can work on all OS even when it uses forward slashes. I will merge tomorrow.

**Comment by gianugo** [comment]
Awesome Felix, thanks much!

**Comment by felixfbecker** [comment]
#5
