### ISSUE TITLE
Debug crashed

### ISSUE THREAD

**Issue by thanhhungtn1** [felixfbecker/vscode-php-debug#30]
When do debug there's an alert message like this and can't debug.

![image](https://cloud.githubusercontent.com/assets/8663216/14374026/339fb3fa-fd7b-11e5-9c03-f9b1a95c2c71.png)

**Comment by felixfbecker** [comment]
Could you please try out the 1.6 prerelease?

**Comment by glen-84** [comment]
I just had the same issue, and it was because the port was already in use (by Eclipse I think).

**Comment by felixfbecker** [comment]
Hm, if the TCP server or socket emits an error event the error should get printed to the debug console before the adapter exits...
@weinand is there a way to get the stderr output of a debug adapter when it crashes, eg the stack trace and exception message? Is it printed to the console in the dev tools?

**Comment by glen-84** [comment]
I saw something in the console. It may have been `EADDRINUSE`, but there was no stack trace IIRC.

**Comment by felixfbecker** [comment]
Yeah then that is actually the proper error handling here: https://github.com/felixfbecker/vscode-php-debug/blob/e980a155684af20b504467ff0df6f27328901e05/src/phpDebug.ts#L253. When the TCP server emits an error I print it to the debug console and terminate the adapter. EADDRINUSE should indeed give you the hint that the port is already occupied.

**Comment by glen-84** [comment]
Tested it again, and the message is `listen EADDRINUSE :::9000`.

I almost missed it the first time because there was just a small console icon with a red circle over it, which is initially covered by the error that you see in the screenshot above.

**Comment by felixfbecker** [comment]
There is nothing I can do about it, VS Code does not allow debug adapters to show error messages to the user at arbitrary times :/

**Comment by weinand** [comment]
@felixfbecker I suggest to file a feature request for adding support for asynchronous error messages. In the meantime you can send asynchronous error messages as an output event with category `console`. They will show up in the debug console in orange.
In addition a discussion has started about where to log the stderr messages of the debug adapter: https://github.com/Microsoft/vscode/issues/5832. Please feel free to chime in...

**Comment by bascoder** [comment]
I had the exact same issue has @thanhhungtn1 

I **resolved** the issue by reinstalling the extension using vscode.

==
Currently I'm using vscode version:
```
1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44
```

==
When experiencing the issue I was already using the lastest version of this extension.

**Comment by felixfbecker** [comment]
If it was EADDRINUSE, reinstalling would not have helped.
@glen-84 I consider this resolved so closing :)
