### ISSUE TITLE
Disable displaying of specific errors/warnings is VS Code.

### ISSUE THREAD

**Issue by skorunka** [felixfbecker/vscode-php-debug#300]
PHP version:  7.2
XDebug version: 2.6.1 
Adapter version: 1.12.5

Your launch.json:  
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9000
		},
		{
			"name": "Launch currently open script",
			"type": "php",
			"request": "launch",
			"program": "${file}",
			"cwd": "${fileDirname}",
			"port": 9000
		}
	]
}
```

XDebug php.ini config:
```
zend_extension="c:\xampp\php\ext\php_xdebug-2.6.1-7.2-vc15.dll"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_handler = dbgp
xdebug.remote_host = 127.0.0.1
xdebug.remote_port = 9000
xdebug.remote_mode = req
xdebug.idekey="php-vs"
```
Code snippet to reproduce:

```php
$_GET["xxx"] // when the $_GET is empty
```
![image](https://user-images.githubusercontent.com/218913/44921836-90dedb00-ad3b-11e8-8d95-f884c7995056.png)

I would like to disable such an errors while debugging. 

PS: fixing those errors(with `isset()`) is not an option at the moment :(

**Comment by felixfbecker** [comment]
This is supported. Untick "Notices" in the bottom left of the debug panel.

**Comment by skorunka** [comment]
Works, thanks.
