### ISSUE TITLE
意外停止调试

### ISSUE THREAD

**Issue by JavenQue** [felixfbecker/vscode-php-debug#305]
Issue Type: <b>Bug</b>

意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试意外停止调试

Extension version: 1.12.5
VS Code version: Code - Insiders 1.28.0-insider (29e6dce4352db76d8956035990b8630580226588, 2018-09-14T08:23:30.210Z)
OS version: Windows_NT x64 10.0.18237

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.00GB free)|
|Process Argv|D:\Microsoft VS Code Insiders\Code - Insiders.exe D:\phpStudy\PHPTutorial\www\HuangJia"|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by felixfbecker** [comment]
Google Translate:

> Unexpected stop debugging
> Accidental Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debugging Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debug Unexpected Stop Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping Debugging Unexpectedly Stopping

Sorry, but I can't make sense out of this, and I don't know Chinese. Please file an issue in English.
