### ISSUE TITLE
recently very slow

### ISSUE THREAD

**Issue by nn-hh** [felixfbecker/vscode-php-debug#327]
PHP version:  5.6, 7.1, 7.2
XDebug version: 1.12.6
windows10
xampp

Wait time of about 3-5 seconds occurs on the notebook PC(ssd).
Difficult to use such as step over.
All of my colleagues in the company have the same symptoms.

Is #308 related to it?

**Comment by Student414** [comment]
When VS Code in background with phpdebug enabled. web server is very slow same.
