### ISSUE TITLE
Excluding folder paths from debugging

### ISSUE THREAD

**Issue by VivPat** [felixfbecker/vscode-php-debug#33]
PHP version:  5.6 / 7.0
XDebug version:  2.4.0
Adapter version:  1.7.1

Your launch.json:  

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name"             : "PHP Web Application : XDebug",
            "type"             : "php",
            "request"          : "launch",
            "port"             : 9000,
            "serverSourceRoot" : "E:\\Development\\vps\\LeCoterie\\LeCoterie-Website"
        }
    ]
}
```

XDebug is working, however when verifying how XDebug works within vscode-php-debug versus PHPStorm I see a difference which causes issues with Laravel.

Basically, when I debug via PHPStorm, Laravel is using a plethora of Vendor items, of which some throw exceptions which are handled within the backend of PHPStorm (Testing for RegEx, etc) and doesn't cause any issues.

When I debug via VSCode, the exceptions are caught and by doing so actually stops the application from running as expected.

I am not sure how PHPStorm does it, but would there be any way of excluding paths from debugging, or adding in Exceptions types to be excluded from debugging.

**Comment by felixfbecker** [comment]
XDebug supports "exception breakpoints". Depending on what you select in VS Code under "Breakpoints", different types of exception breakpoints are set. For example, checking "Exceptions" will add an exception breakpoint for `Exception` (which means everything that subclasses `Exception`). "Notices" will set a breakpoint for `Notice`. "Everything" will set a breakpoint for `*`, which means any error. I am not aware of a way to only break on uncaught exceptions, and I think that not breaking on any exceptions in `/vendor` would not be a good idea...

**Comment by VivPat** [comment]
Good day Felix,

Unfortunately I cannot afford to turn off **exception** breakpoints as that would stop the debugger from capturing any exceptions that I may need to throw and test.

By no means do I know how it has been done, but PHPStorm does not catch **vendor** exceptions but does however catch exceptions that I throw.

Currently, within VSCode if the Debugger breaks on the **exceptions** within /vendor then for some reason API requests from within my application do not complete.

This does not occur when using XDebug within PHPStorm.

**Comment by felixfbecker** [comment]
Could you point me to PHPStorm's documentation of that behaviour? I don't see the benefit of not stopping on exceptions in /vendor

**Comment by apit** [comment]
this is one of those Laravel code:

```php
foreach ($request->cookies as $key => $c) {
    // ... snip
    try {
        $request->cookies->set($key, $this->decryptCookie($c));
    } catch (DecryptException $e) {
        $request->cookies->set($key, null);
    }
}
```

cookie that set by frontend js (so, not encrypted) will throw exception. 

could Code be configured to only catch uncatched Exception, or ignored if coming from certain path (like /vendor)?
