### ISSUE TITLE
Browser loading forever in "Listen for XDebug" mode

### ISSUE THREAD

**Issue by lesydat** [felixfbecker/vscode-php-debug#34]
PHP version:  5.6.8
XDebug version:  2.4.0
Adapter version:  

Your launch.json:  
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "serverSourceRoot": "/Applications/XAMPP/xamppfiles/apache2/htdocs/test/testproject",
            "localSourceRoot": "${workspaceRoot}",
            "port": 9000,
            "log": true
        },
        {
            "name": "Launch",
            "request": "launch",
            "type": "php",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "externalConsole": false
        }
    ]
}
```
XDebug php.ini config:  
```
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.remote_log=/var/log/xdebug.log
```
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php
echo "hello word!";
```
I'm using vscode with xdebug. When I test with Launch currently open script, it work but not stop at breakpoint, when I test with Listen for Xdebug, browser loading forever and nothing display.
My web server running on the same machine as VS Code.

**Comment by felixfbecker** [comment]
Can I please know
 - your adapter version
 - the xdebug section of `phpinfo()`
 - XDebug logfile (from setting  xdebug.remote_log  in php.ini)
 - Adapter logfile (from setting  "log": true  in launch.json)

If VS Code is running on the same machine as your webserver, you dont need `localSourceRoot`/`serverSourceRoot` and also not `remote_host`.

**Comment by felixfbecker** [comment]
Closing for lack of response.
