### ISSUE TITLE
Is there a version that works with PHP 5.6? [help wanted]

### ISSUE THREAD

**Issue by ErnestoBorio** [felixfbecker/vscode-php-debug#342]
This is of course not an issue, but a question or request, since there's no other place suitable for it.
I would prefer to use the latest PHP version, but sadly I have to use 5.6 per client's requirements.
Is there a version of this extension that runs with PHP 5.6?
Thanks.

PS: I can't find anywhere how to ad labels to the issue.

**Comment by SidIcarus** [comment]
@ErnestoBorio 

The extension Travis builds for `5.6.3`. Also, I was using the extension with version `5.3.3` last year so it is most likely a configuration issue on your end. I would go through your extension, php, and network configurations.
