### ISSUE TITLE
Is there a configuration variable for "document root"?

### ISSUE THREAD

**Issue by JacobDB** [felixfbecker/vscode-php-debug#348]
I'm trying to set up my launch.json in such a way that it can be copied from project to project without modification. It's almost there, except for this. I'd like to replace the server document root path with a variable, but I can't find this documented anywhere. Is there a way to specify a variable in the `pathMappings` that equates to `$_SERVER['DOCUMENT_ROOT']`?

**Comment by bilogic** [comment]
Are you referring to the ```key``` or ```value``` part?
```
"/remote/server/folder/aka_key": "${workspaceFolder:name_of_local_folder_aka_value}",
```
1. The variables ```${workspaceFolder:...}``` are by vscode and not ```vscode-php-debug```, also vscode does not have any mechanism to retrieve ```$_SERVER['DOCUMENT_ROOT']``` from the server, so this option is a no-go
2. I could be wrong, but don't think the ```key```  accepts variables. You could try, I'm curious to know too.
3. If .2 works, I think you can name your local folders to match your remote folders, this way you get what you want, but not by retrieving ```$_SERVER['DOCUMENT_ROOT']```. 

Hope it helps.

List of all variables here: https://code.visualstudio.com/docs/editor/variables-reference

**Comment by JacobDB** [comment]
Ah, thanks for the clarification. I was thinking of this only in the context of running a development server locally so I assumed it'd be possible to get that variable, but I also didn't realize that those variables are set by VS Code.
