### ISSUE TITLE
What is the idekey ??

### ISSUE THREAD

**Issue by simlevesque** [felixfbecker/vscode-php-debug#38]
Hi, I want to setup remote debugging and I need to know what is the idekey for vscode.

**Comment by felixfbecker** [comment]
The IDE key is currently not used by VS Code :)

**Comment by X-Coder** [comment]
How is it possible to use it on a shared rdp server with multiple developers, each working in his own debug session? See [this page](https://confluence.jetbrains.com/display/PhpStorm/Multi-user+debugging+in+PhpStorm+with+Xdebug+and+DBGp+proxy) for explanation on how to setup a dbg proxy.

Does this only require a patch for matching the idekey against a vscode config option to get it working?

**Comment by X-Coder** [comment]
Just found [this pull request](https://github.com/felixfbecker/vscode-php-debug/pull/111), hope you can find a way to get this working, this is exactly what I was searching for.

**Comment by MurzNN** [comment]
@X-Coder is this pull request still needed, or support for IDEKEY is implemented already in later versions of extension?
