### ISSUE TITLE
Array of arrays variable not showing in Watch window

### ISSUE THREAD

**Issue by petke** [felixfbecker/vscode-php-debug#390]
For a array of arrays variable, the items show up in "Locals" but are not shown when in in "Watch".

![watch](https://user-images.githubusercontent.com/822399/74148781-84d09b80-4c06-11ea-954b-79798e1c4b64.png)

PHP version:  PHP Version => 7.3.12
XDebug version:  Xdebug v2.8.0
Adapter version:

Your launch.json:  
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        },
        {
          "name": "My Launch",
          "request": "launch",
          "type": "php",
          "program": "${file}",
          "cwd": "${workspaceRoot}",
          "externalConsole": false,
          "stopOnEntry": true,
          "runtimeExecutable": ""
        }        
    ]
}

(I added an use the "My Launch" as debugger doesn't stop on breakpoints otherwise)

XDebug php.ini config:

[xdebug]
zend_extension="c:/wamp64/bin/php/php7.3.12/zend_ext/php_xdebug-2.8.0-7.3-vc15-x86_64.dll"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
#xdebug.remote_enable = off
xdebug.profiler_enable = off
xdebug.profiler_enable_trigger = Off
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.profiler_output_dir ="c:/wamp64/tmp"
xdebug.show_local_vars=0

Code snippet to reproduce:

```php

<?php


$cars = array
(
array("Volvo",22,18),
array("BMW",15,13),
array("Saab",5,2),
array("Land Rover",17,15)
);

echo "";

?>
```

**Comment by petke** [comment]
I found a workaround. Modifying launch.json so xdebugSettings max_depth": 7 makes it work

        {
          "name": "My Launch",
          "request": "launch",
          "type": "php",
          "program": "${file}",
          "cwd": "${workspaceRoot}",
          "externalConsole": false,
          "stopOnEntry": true,
          "runtimeExecutable": "",

          "xdebugSettings": {
            "max_depth": 7,
          },
        }

**Comment by MurzNN** [comment]
Thanks for solution, it works well! But why default "max_depth" is so small?

And maybe this extension can expand needed variables on demand? Eg, when user opens some deeper level - re-require variable info with deeper level, or re-require only current subtree? Is this possible?
