### ISSUE TITLE
PHP Debug Extension influencing PHP max_execution_time/set_time_limit?

### ISSUE THREAD

**Issue by MikeyF-Anovia** [felixfbecker/vscode-php-debug#415]
PHP version:  Version 7.1.25
XDebug version:  2.7.0
Adapter version: 1.13.0

Your launch.json:  { "name": "Listen for XDebug", "type": "php", "request": "launch", "port": 9000, "xdebugSettings": { "max_children": 256, "max_data": 256, "max_depth": 4, "show_hidden": 0 } }

XDebug php.ini config:
zend_extension=php_xdebug-2.7.0-7.1-vc14-nts-x86_64.dll
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.coverage_enable=0
xdebug.default_enable=0
xdebug.var_display_max_depth=8
xdebug.var_display_max_children=256
xdebug.var_display_max_data=512
xdebug.profiler_enable=0
xdebug.profiler_output_dir="C:\Users\Mikey\Documents\GitHub\ap-trio\app\tmp\logs"

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  (none)
Adapter logfile (from setting `"log": true` in launch.json): (none)

Code snippet to reproduce:

```
    set_time_limit(1);
    ini_set('max_execution_time', 1);
```

I'm not really sure what is to blame here--VS Code, xDebug or the PHP Debug extension? And I've tried searching under all of them. I am wanting to debug issues with Maximum execution time outs in my app so I can add some err handling and logging. I am setting time limit and max_exec times to 1 second via php.ini and code and yet something is setting it to 0 when I debug. It is making it difficult to debug exec time outs in my app. 
I was noticing that my PHP Info shows a Local Value of 0 and a Master Value of 1 while debugging. My settings arent being honored. If I click Stop (to stop PHP debugging in VS Code) PHP Info then shows a Local Value as 1 and my app experiences the timeout error if I try executing something longer than 1 second. Is the PHP Debug extension setting a max time out of 0 while in debug mode? 
Thanks
-Mikey

**Comment by AnrDaemon** [comment]
When active debug session is in progress, `max_execution_time` is ineffective.

**Comment by MikeyF-Anovia** [comment]
Ok. Thanks
