### ISSUE TITLE
PhP Debugging no longer working since latest VSCode Update

### ISSUE THREAD

**Issue by wildcat9** [felixfbecker/vscode-php-debug#418]
Hello Felix,

I hope you're well, firstly let me thank you for the awesome work you've done with this plugin it truly is a great tool when working with Php and VSCode. I have noticed that Php Debugging stopped working recently since the latest VSCode update. I'm not sure if there are changes that affect this plugin but it's sadly no longer works for any breakpoints I add anywhere. One thing that does work is the debugger does break on exceptions. Please review my data and logs below.

PHP version:  7.4.8
XDebug version:  2.96
Adapter version: 1.13.0

Your launch.json:  
[launch_json.txt](https://github.com/felixfbecker/vscode-php-debug/files/5131581/launch_json.txt)

XDebug php.ini config:

xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_host=host.docker.internal
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.show_error_trace=1
xdebug.var_display_max_depth=15
xdebug.remote_log=\"/code/logs/xdebug.log\"
xdebug.idekey=VSCODE
xdebug.remote_mode=req
xdebug.profiler_enable=0
xdebug.remote_connect_back=0

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
[xdebug.log](https://github.com/felixfbecker/vscode-php-debug/files/5131576/xdebug.log)

Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
phpinfo(); // Break point added on this statement or any other doesn't work
```

**Comment by brunob** [comment]
Dup of #414 see https://github.com/VSCodium/vscodium/issues/466
