### ISSUE TITLE
Setting up with vagrant help

### ISSUE THREAD

**Issue by c0cky** [felixfbecker/vscode-php-debug#42]
I'm trying to set up xdebug with vagrant but am confused on how to start.

**Comment by felixfbecker** [comment]
Sorry, I never used Vagrant, I don't even know what it is. Maybe you can get help from other users on Gitter or StackOverflow.

**Comment by c0cky** [comment]
my xdebug is running on a virtual machine that is deployed by vagrant and my php.ini looks like this
```
xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_host=10.0.2.2
xdebug.remote_port=9000
xdebug.remote_autostart=1
```

**Comment by c0cky** [comment]
I fixed it by adding 

`xdebug.remote_log=/var/log/xdebug.log`
to my php.ini and adding 

`"log": true`

**Comment by poproar** [comment]
@c0cky I set this up with log true and I finally get a launch response in the debug console :
```
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
```
but that is it, not able to step into anything or watch variables
what are your launch.json settings?

**Comment by felixfbecker** [comment]
log and remote_log don't have anything to do with this. You need to set `localSourceRoot` to `${workspaceRoot}` and `serverSourceRoot` to the equivalent path on your Vagrant VM.
