### ISSUE TITLE
XDebug 3.x and PHP 8.0/7.4

### ISSUE THREAD

**Issue by bseddon** [felixfbecker/vscode-php-debug#436]
PHP version:  8.0 (and 7.4.x)
XDebug version:  3.x

As you probably know, XDebug 3.0 makes some changes that affect .ini settings.  The text of the welcome page still refers to the settings required for XDebug 2.x.  The changes are documented on the [XDebug upgrade page](https://xdebug.org/docs/upgrade_guide).

There are three changes that are relevant:

**mode**

Users should ensure there is a line in the ini file like:

xdebug.mode=debug

**port**

The default port is now 9003 so user either needs to reference this port in their launch configuration instead of 9000 or make sure the port is the same in the ini and launch configuration.

**remote_autostart**

This is now changed and replaced with 'start_with_request' which can have the values of 'yes' or 'trigger'.  For example:

xdebug.start_with_request=yes

'trigger' allows a debug session to start when the statement ' xdebug_break()' is executed.

**Comment by AnrDaemon** [comment]
To clarify: This is not a problem in extension per se. It is merely a documentation issue.
