### ISSUE TITLE
Debugger hits removed breakpoints on Windows

### ISSUE THREAD

**Issue by JoelOnGithub** [felixfbecker/vscode-php-debug#44]
Issue: When I hit the first breakpoint on line 4, then remove the breakpoint on line 4 and click continue, I will still keep hitting what used to be the breakpoint on line 4.

When I do exactly the same thing with XDebug in Atom, this doesn't happen.

PHP version:  5.6.16
XDebug version:  php_xdebug-2.4.0-5.6-vc11-x86_64.dll
Adapter version:  

Your launch.json:   [link](http://pastebin.com/EPArsswP)

XDebug php.ini config: [link](http://pastebin.com/BXzK12wg)

XDebug logfile (from setting `xdebug.remote_log` in php.ini): [link](http://pastebin.com/wEnvVGZt)

Adapter logfile (from setting `"log": true` in launch.json): [Sorry for the weird indents](http://pastebin.com/upVN1SSJ)

Code snippet to reproduce:  
```php
<?php

for( $i = 0; $i < 2; $i++ ){
	echo $i;
}

phpinfo();

?>
```

**Comment by felixfbecker** [comment]
@JoelOnGithub I know it is hard to copy from the debug console, but I need to inspect the setBreakpointRequests... could you please copy it? You have to do it one page at a time

**Comment by JoelOnGithub** [comment]
Haha oh man! Updated :)

**Comment by felixfbecker** [comment]
Try this one please
[php-debug-1.9.1.vsix.zip](https://github.com/felixfbecker/vscode-php-debug/files/322326/php-debug-1.9.1.vsix.zip)

**Comment by JoelOnGithub** [comment]
I see no difference in behavior

**Comment by felixfbecker** [comment]
Could you get the logs again with that version?

**Comment by JoelOnGithub** [comment]
[debug console](http://pastebin.com/A4aCefiQ)
[xdebug php log](http://pastebin.com/0ZJxVEWf)

**Comment by felixfbecker** [comment]
Please see if 1.9.2 fixes your problem

**Comment by JoelOnGithub** [comment]
Yes it has been fixed! Thank you very much. You can close the ticket.

Just out of curiosity, can you tell me what was going wrong?

**Comment by felixfbecker** [comment]
Well, to update the breakpoints, I get them all, then remove them all for the file in question, and then re-set them. First of all, when parsing the XDebug response, I forgot to set the `fileUri` property on the LineBreakpoint object, so it was always `undefined` and never matched. Secondly, VS Code sends a file path like `c:\hello_world` on Windows (lowercase drive letter), while XDebug always sends `file:///C:/hello_world` (uppercase drive letter) so I had to compare them case-insensitive on Windows. Look at 34be582813fae54256fee948b37502a3f0a83fc1 and 3d8434120440a90bee92efce6d94cb4a77b384ed if you are interested. I also added a test for this in f71fa26767cb5fc4f48a3739b61354761c435125, but for some reason it fails in CI (it passes on my machine).

**Comment by JoelOnGithub** [comment]
Thanks for the explanation!

**Comment by bilogic** [comment]
Hi,

This is happening for me now in VSCode 1.37.1
PHP Debug Adapter: 1.13.0
PHP 7.2.10 (cli) (built: Sep 11 2018 09:59:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

**Comment by bilogic** [comment]
This is from my debug console, from what I gather, there are no more breakpoints, yet it breaks again if I ```Continue (F5)```

```
-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'layout_controller.php',
        path:
         'e:\\project\\layout_controller.php' },
     lines: [],
     breakpoints: [],
     sourceModified: false },
  type: 'request',
  seq: 22 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 22,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [] } }
```
