### ISSUE TITLE
Invalid Version: 2.4.0RC

### ISSUE THREAD

**Issue by hkm-mo** [felixfbecker/vscode-php-debug#47]
Debug shown a message, "Invalid Version: 2.4.0RC3" and stopped at first line.

PHP version:  7.0.8
XDebug version:  2.4.0RC3
Adapter version:  19.2

**Comment by felixfbecker** [comment]
I'm parsing the versions with semver, which wants a version like `2.4.0-RC3`. You can fix the issue by updating to 2.4.0 stable

**Comment by felixfbecker** [comment]
Should be fixed in 948446a93fa2ebd4b10f26056a1d1caa2f2c8542
