### ISSUE TITLE
some expression on watch can not expand

### ISSUE THREAD

**Issue by illlust** [felixfbecker/vscode-php-debug#52]
![xdebugwatch](https://cloud.githubusercontent.com/assets/475315/17267526/90de0ce6-5646-11e6-82be-a0edda7301bc.png)

hi. first, thank you. who made this awesome app.

in my screenshot, first block and second block are same object reference.

and local variable $this->defaultSettings is expandable own array elements,
but $this expand defaultSettings expression on watch, can not. T_T

I'm reading xdebug.log, and first VARIABLES command is 'eval', second WATCH is 'property_get', maybe.

I don't know about xdebug well, so don't know it is bug or original operations...

but i used often watch more than variables...
cause too many variables makes me hard to find i want.
so it's operation can be changeable, i want to... T_T

sorry about that my poor english :D

----

PHP version:  7.0 fpm (PHP Version 7.0.8-4+deb.sury.org~trusty+1)
XDebug version:  2.4.0
Adapter version:  1.9.4

Your launch.json:  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9001,
            "log": false,
            "stopOnEntry": false,
            "serverSourceRoot": "/home/mike/myapp",
            "localSourceRoot": "${workspaceRoot}"
        }
   ]
}

XDebug php.ini config:  
zend_extension=xdebug.so
xdebug.default_enble=1
xdebug.profiler_enable=0
xdebug.var_display_max_data=512
xdebug.collect_assignments=1
xdebug.collect_includes=1
xdebug.collect_params=4
xdebug.collect_return=1
xdebug.collect_vars=1
xdebug.coverage_enable=0
xdebug.max_nesting_level=512
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=0
xdebug.remote_connect_back=0
xdebug.remote_host=127.0.0.1 ; ssh tunnel
xdebug.remote_port=9001
output_buffering=0
xdebug.remote_log="/tmp/xdebug.log"
xdebug.show_exception_trace=0
xdebug.show_local_vars=1
xdebug.cli_color=0
xdebug.scream=0
xdebug.var_display_max_depth=-1
xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
attachment

Adapter logfile (from setting `"log": true` in launch.json):

**Comment by illlust** [comment]
[xdebug.3.log.txt](https://github.com/felixfbecker/vscode-php-debug/files/391692/xdebug.3.log.txt)

**Comment by felixfbecker** [comment]
Also happens in the debug console (as it both goes through `evalRequest`)

**Comment by koca** [comment]
+1

**Comment by illlust** [comment]
thx a lot! :D

**Comment by nickchomey** [comment]
I appear to be having this issue. I just updated to xebug 3.1.4, but that didnt help. 

As you can see, the $bp global variable for buddypress can be expanded in the Variables Pane but not in the Watch Pane. Moreover, if I watch a specific property of the global variable (e.g. $bp->data) it returns `null`.
![image](https://user-images.githubusercontent.com/88559987/166800267-b7f5956a-2ddc-4db2-9449-eb83fa6ab0a7.png)
