### ISSUE TITLE
Option to disable automatic exception breakpoints, break only at explicit points

### ISSUE THREAD

**Issue by mitchellnemitz** [felixfbecker/vscode-php-debug#56]
Please include the ability to disable automatic breakpoints, this extension is all but useless for debugging older code without it. I have inherited an ancient application built on a terrible homemade framework that constantly throws exceptions for small things, I don't want to click continue 100+ times before I can get to my own explicit breakpoint and fix actual feature code.

If you could point me to where the automatic breakpoints are configured / set, I can fork and solve this issue myself, but my understanding of the GDBp is limited, and TypeScript is somewhat foreign, so I need some direction.

Thanks.

----

PHP version:  5.6.22
XDebug version:  2.4.1
Adapter version:  1.9.4

Your launch.json: 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "localSourceRoot": "/Users/mitchell/dev/git",
            "serverSourceRoot": "/mnt/git/"
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

**Comment by felixfbecker** [comment]
This should disable breaking on any kind of error
![image](https://cloud.githubusercontent.com/assets/10532611/18137034/2541b166-6fa7-11e6-8ae1-6bc855ae5ad3.png)

**Comment by mitchellnemitz** [comment]
I am an idiot. Thanks.

**Comment by aNickzz** [comment]
Is there a way to break only on un-caught exceptions (like chrome dev tools)?

**Comment by felixfbecker** [comment]
@aNickzz that is not exposed by XDebug

**Comment by knetworx** [comment]
I definitely don't have those options under the breakpoint bar. I've restarted the app and all that, made sure the breakpoints bar was expanded, etc.

**Comment by felixfbecker** [comment]
@knetworx did you run the debugger at least once? It needs to return those options to VS Code at least once

**Comment by knetworx** [comment]
I've tried to, but I think I've got something wrong in my setup. It seems to die immediately.
<img width="1540" alt="screen shot 2018-04-11 at 9 17 49 pm" src="https://user-images.githubusercontent.com/3292803/38656408-2c553480-3dcf-11e8-8ea5-1be7f3c9f599.png">
We have a very complex project, and I'm trying to figure out the build process so I can debug in VSCode rather than XCode, but it's not my area of expertise, so I'm fumbling through it.

**Comment by felixfbecker** [comment]
Seems like a different issue / problem with your setup. Please open a new issue and include the logs in the issue template

**Comment by knetworx** [comment]
I figured it out, I just needed to set my DYLD_LIBRARY_PATH in my launch.json, like this:
```
"environment": [
	{
		"name": "DYLD_LIBRARY_PATH",
		"value": "bin"
	}
],
```

**Comment by lutonda** [comment]
![image](https://user-images.githubusercontent.com/1699809/43866133-9f97b090-9b5c-11e8-8afb-1c87b6887c71.png)

**Comment by cjwijtmans** [comment]
XDebug breaking on exceptions that are being caught is extremely annoying and breaks good code design...
