### ISSUE TITLE
Add "Max simultaneous connections" ?

### ISSUE THREAD

**Issue by zobo** [felixfbecker/vscode-php-debug#571]
Considering adding "Max simultaneous connections". 
Vote if you need this.

**Comment by dvsoukup** [comment]
+1.  Phpstorm has this.  Would be nice to do to prevent debugger catching in different threads while stepping through something...

**Comment by zobo** [comment]
Interesting. Would an ability to stop listening for new connections be equally useful? I could interpret this setting as, "show me max 3 parallel connections, more than that I can't deal with anyway".
I saw an old report that PhpStorm has this, and I'm considering adding it.

**Comment by derickr** [comment]
FWIW, I was checking yesterday how I can make it stop listening for incoming connections. I think this can be useful for people that have `xdebug.start_with_request` set to `yes`, as every request to PHP will (try to) generate a debugging session, and... I don't always want to debug every request.
