### ISSUE TITLE
Support no folder debugging

### ISSUE THREAD

**Issue by isidorn** [felixfbecker/vscode-php-debug#638]
Hi VS Code PM here 👋 

1. Purple no folder VS Code -> create a new php file
2. Press `F5` -> notice how we offer the user to download your extension 👏 
3. Now the user presses `F5` again and wants to debug, but nothing happens since php-debug is not supporting single folder debugging

Easiest to do this is to have a dynamic `resolveDebugConfiguartion` that will provide a launch configuration on the fly. [Example](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L161)

Apart from that consider contributing to the Editor title area menu, such that a Play button would appear in the Editor Title area (picture below). Example how to do this https://github.com/microsoft/vscode-mock-debug/blob/main/package.json#L80

I think both of these are super important and would really love that we improve this experience 💯  
Let me know if I can help somehow. I am also open to a quick 30 min meeting where we can discuss about the new cool VS Code debug features that php-debug could potentially adopt.

fyi @weinand

![Screenshot 2021-08-26 at 16 03 43](https://user-images.githubusercontent.com/1926584/130977065-c1c78f34-ed0f-4735-9f45-5068cbba1119.png)

**Comment by isidorn** [comment]
As we discussed in the meeting, here are some of the cool features that php-debug could adopt. @weinand and @roblourens please jump in with ideas.


<details>
  <summary>No folder debugging as mentioned above</summary>
  
  Easiest to do this is to have a dynamic `resolveDebugConfiguartion` that will provide a launch configuration on the fly. 
[Example](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L161)
</details>

<details>
  <summary>Contribute to debug start</summary>
  This should have commands that help user setup and start debugging.
Example and more details in this issue https://github.com/microsoft/vscode-cpptools/issues/4837
</details>

<details>
  <summary>Contribute to inline value providers</summary>
Should allow to have yellow inline values on the side while debugging
More details in this issue https://github.com/microsoft/vscode/issues/105690#117288
</details>

<details>
  <summary>Contribute the play button in editor title area</summary>
Example https://github.com/microsoft/vscode-java-debug/blob/main/package.json#L186
</details>

* Java repo which has a lot of this things implemented as an example https://github.com/microsoft/vscode-java-debug
* Opened this issue based on our discussion https://github.com/microsoft/vscode-docs/issues/4800
* A list of release notes, we always have a section called Debugging so that might be interesting to checkout from time to time https://code.visualstudio.com/updates/v1_59
* Issue for GitHub sponsors which we talked about, feel free to chime in there https://github.com/microsoft/vscode/issues/107482

Feel free to ping us for any questions you might have. And thank you very much for improving php debugging 👏  👏

**Comment by zobo** [comment]
Thanks for all the examples and suggestions. I did a basic implementation for no folder in #645 and will try to further extend it with editor menu contribution.

I will have a look at the other suggestions. I think the "contribute to debug start" is very interesting. Having the extension guide the user through setup would be invaluable. I think this would need to include:
- check if php is in path
- check if it's in some global setting (php.executablePath or php.validate.executablePath?)
- offer the user to set those?
- analyze the php version and possible installed Xdebug version.
- calculate what Xdebug version to download (windows?) 
- change the php.ini files
- ...

**Comment by isidorn** [comment]
@zobo sounds good.

The extension could guide the user through a series of quick picks (if user interaction is needed).

Maybe related to this: if there are different `Xdebug` versions per platform, and if you want to ship `Xdebug` as part of the extension - we are currently working on platform specific extensions https://github.com/microsoft/vscode/issues/23251

**Comment by AnrDaemon** [comment]
> check if php is in path
> check if it's in some global setting (php.executablePath or php.validate.executablePath?)

What if I simply have configured association? (Windows)
"PHP in PATH" is not a Windows way of doing things.

**Comment by zobo** [comment]
Hi. Yes, I do agree that on windows (my primary platform also) people tend to avoid putting everything into PATH. However looking up executables for specific filename extensions feels... wrong. 

I feel providing a VS Code settings variable is the right way to go, in case we can't find php.exe in the PATH.

@isidorn I believe VS Code already uses `php.validate.executablePath` setting for it's internal PHP extension. What would be the best setting to enable the user to set the path to their PHP executable? Perhaps add `php.executablePath` and also check `php.validate.executablePath`?

I'd use this logic for the no-folder debugging and also extend it to when a launch configuration is provided, but not `runtimeExecutable` is set by the user.

Thanks!

**Comment by AnrDaemon** [comment]
> I feel providing a VS Code settings variable is the right way to go, in case we can't find php.exe in the PATH.

[`php.validate.executablePath`](https://code.visualstudio.com/docs/languages/php#_linting)

Already exists.

**Comment by isidorn** [comment]
> Perhaps add `php.executablePath` and also check `php.validate.executablePath`?

This sounds reasonable to me.

**Comment by zobo** [comment]
Hi @isidorn .

I added `editor/title/run` to the extension, but noticed that your example from java (https://github.com/microsoft/vscode-java-debug/blob/main/package.json#L186) uses `when` with `resourceExtname`, but a lot of other examples I found used `languageId`.

```
    "menus": {
      "editor/title/run": [
        {
          "command": "workbench.action.debug.start",
          "when": "resourceLangId == php"
        }
      ]
    },
```

Any hint on what is better and why?

Thanks!

**Comment by isidorn** [comment]
@zobo sorry for the slow response. 
`resourceLangId` is better because it will also work for Untitled files when the user sets the language mode explicitly to `php` (and that file might not yet be on disk and thus does not have an extension).
fyi @testforstephen if java would potentially also change to `resourceLangId`. Or if there are reasons I am missing for using `resourceExtname`?

I would always show it in `editor/title/run`. We noticed that it is just convenient for users to click there unrelated if there is a `launch.json` or not. Though I leave this up to you as to whatever you think is best.

Thanks for working on this 👏

**Comment by weinand** [comment]
@zobo I'm now back from vacation...

> Also, would it make sense to show the editor/title/run button only when there is no launch.json?
No, the editor's run/debug menu is independent ("orthogonal") to the launch.json. This makes it possible to run or debug the editor contents without being affected by anything configured in the launch.json.

I've noticed that you are using the `workbench.action.debug.start` action in the "editor/title/run" contribution. This is not a good choice because this action just runs the selected launch config (which can be anything).

You must create and register your own `php`-specific command  in your extension. Please see how this is done in Mock Debug: https://github.com/microsoft/vscode-mock-debug/blob/6a3df6d2e8bed44408f137d61053b8a8c020523f/src/activateMockDebug.ts#L15-L45

**Comment by zobo** [comment]
Hi Andre.

Thanks for your input, I was already leaning into this direction as I saw java implemented it like this - I just didn't get around changing it yet.

Since I have you both here, there is another situation I wanted to ask about:
One typical mode of operation for a DBGP client could be described as "read only" mode. Here, the IDE/Client would listen for DBGP connections from PHP, typically from a remote server. When a connection is established all files are downloaded over the DBGP connection on a request basis. All this is already doable within the Debug Adapter Protocol.

So what I'm asking is, what would be the best way to use VS Code as a standalone/no-folder/no-files tool? All this can be configured with `launch.json` properties, but I think I'd like to have a button or menu item for the user to trigger this feature.

Does this sound familiar to anything somebody else is doing?

Thanks!

**Comment by isidorn** [comment]
@zobo I am not aware of anyone else doing something like this.

A potential entry point for this would be in the Debug Welcome View, or you could add a Command Palette Entry.
I am not sure where else would this command fit best.

@weinand might have better ideas.

**Comment by zobo** [comment]
Yes, I did think about Debug Welcome View and will definitely try that, but I think that is only available when there is no lunch config.
It might be enough in this case, just wondered if there's an option to add it under Run menu or something...

**Comment by zobo** [comment]
@weinand 
> I've noticed that you are using the `workbench.action.debug.start` action in the `editor/title/run` contribution. This is not a good choice because this action just runs the selected launch config (which can be anything not even related to `php`).
> 
> You must implement and register your own `php`-specific command in your extension and use that command in the `editor/title/run` contribution. And the implementation must handle all the possible cases, e.g. "no folder" debugging, no php installed, etc.

I have added a special command `php.debug.debugPhpFile` https://github.com/xdebug/vscode-php-debug/blob/462fe248af6b772844480a3f3dc47aa5584fb97c/package.json#L435 that just initiates a no-folder debug session. The filter on the menu and command should prevent it being used in any other case - as far as I understand it.

**Comment by weinand** [comment]
@zobo yes, the contributed "php.debug.debugPhpFile" command will only be visible if the editor's contents is of language type "php"

**Comment by zobo** [comment]
> @zobo yes, the contributed "php.debug.debugPhpFile" command will only be visible if the editor's contents is of language type "php" 

Correct, but until I added the condition on the `commands` part it was always accessible in the palette (Ctrl-P >). Hope I caught all the cases :)
