### ISSUE TITLE
VSCode: Contribute to inline value providers

### ISSUE THREAD

**Issue by zobo** [felixfbecker/vscode-php-debug#671]
Should allow to have yellow inline values on the side while debugging
More details in this issue microsoft/vscode/issues/105690

_Originally posted by @isidorn in https://github.com/xdebug/vscode-php-debug/issues/638#issuecomment-910541057_

**Comment by ayasario** [comment]
Hopefully this feature will be implemented it is a must have for every debugger

**Comment by ivanaugustobd** [comment]
👀

**Comment by zobo** [comment]
I know I know... :)

**Comment by zobo** [comment]
I have dug into this and as suspected this cannot be implemented in this extension alone. I have implemented it in https://github.com/zobo/php-language-server/pull/59 but other LSPs could also provide it. I need to inspect https://github.com/phpactor/phpactor and vscode-intelephense

**Comment by zobo** [comment]
https://github.com/zobo/vscode-php-intellisense/pull/65
