### ISSUE TITLE
Remote debug not working

### ISSUE THREAD

**Issue by diomabros** [felixfbecker/vscode-php-debug#677]
When select "Listen for XDebug", it not wait for incoming connection but run the debugger, execute the opened PHP script and stop. Any suggestions? (Excuse me for my - bad - english!)

PHP version: 8.0.1
Xdebug version: 3.0.2
VS Code extension version: 1.21.0

Your launch.json: {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 10000,
            "log": true,
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 0,
            "runtimeArgs": [
                "-dxdebug.start_with_request=yes"
            ],
            "env": {
                "XDEBUG_MODE": "debug,develop",
                "XDEBUG_CONFIG": "client_port=${port}"
            }
        },
        {
            "name": "Launch Built-in web server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": [
                "-dxdebug.mode=debug",
                "-dxdebug.start_with_request=yes",
                "-S",
                "localhost:0"
            ],
            "program": "",
            "cwd": "${workspaceRoot}",
            "port": 9003,
            "serverReadyAction": {
                "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
            }
        }
    ]
}

Xdebug php.ini config: 

xdebug.remote_autostart = 1
xdebug.remote_enable = 1
xdebug.client_port = 10000
xdebug.mode = debug
xdebug.discover_client_host = 1
xdebug.start_with_request = yes
xdebug.remote_connect_back = 1

**Comment by diomabros** [comment]
I just deleted lanuch.json and recreated but nothing changes. When I click start button it become orange but, after the PHP error in debug console, it return blue

Before start
![immagine](https://user-images.githubusercontent.com/18497391/138247912-71e7c144-d3bf-4499-9d9e-cab3dd50a304.png)

During script execution
![immagine](https://user-images.githubusercontent.com/18497391/138247717-62ae6ad2-371a-4807-8308-b5cde6b0b894.png)

After script execution
![immagine](https://user-images.githubusercontent.com/18497391/138247861-99583849-19ec-4043-8e1b-c1ac87cd4a32.png)

**Comment by zobo** [comment]
That looks all ok. 

Can you try to switch to an older version of the plugin, specifically 1.19.0 

![image](https://user-images.githubusercontent.com/2456026/138253645-89b6986d-0979-4d6a-94cd-be0d79bb2cb8.png)

![image](https://user-images.githubusercontent.com/2456026/138253716-e46fbc87-fd65-4664-bbff-28a2b413c70f.png)

I introduced new functionality in 1.20.0 that manipulates the debug configuration config... But I have not seen it do something like this.

Do you perhaps have some other extension that could cause this?
