### ISSUE TITLE
PHP Extensions Pack for VS Code

### ISSUE THREAD

**Issue by sandy081** [felixfbecker/vscode-php-debug#78]
@felixfbecker We have introduced a new concept called Extension packs in [1.6 release](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#preview-extension-packs). As an example I have created a temporary [PHP Pack](https://marketplace.visualstudio.com/items?itemName=sandy081.php-pack) with two of your PHP extensions `felixfbecker.php-debug` and `felixfbecker.php-intellisense`. This was created just for examples in our release notes. I would be removing them

I am reaching out to you because, it would be great if you have any idea of publishing an extension pack for PHP with a good PHP related extensions. It would be a good reference for packs and also helpful to the community looking for PHP extensions.

Thanks

**Comment by felixfbecker** [comment]
Hi @sandy081, I already thought about creating such an extension pack myself when I read your release notes. Is it possible to transfer ownership on that package to me so I can update it at will?

**Comment by sandy081** [comment]
@felixfbecker As I said, I created it temporarily just to have some references in our release notes. I removed it from the market place thinking that you would be the best person to do that.

Anyway, Here is the git repository for [PHP Pack](https://github.com/sandy081/vscode-php-pack) I created. Feel free to fork, change and publish.

Thanks.

**Comment by felixfbecker** [comment]
Published under https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-pack
