### ISSUE TITLE
File path doesn't work when spaces in the file/folder name

### ISSUE THREAD

**Issue by nfplee** [felixfbecker/vscode-php-debug#87]
I have just installed the PHP Extension Pack and opened my folder to my PHP project. I noticed a bunch of warnings and when I click on the warning I get the error "Unable to open 'File.php': File not found (c:\...My+Folder\File.php)." I copied the path to Windows file explorer and it could not find the file. However if I replace the + with a space then it opens the file.

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/130
