### ISSUE TITLE
Getting error: "Invalid Version: 2.5.0rc1"

### ISSUE THREAD

**Issue by bunchjesse** [felixfbecker/vscode-php-debug#88]
The debug console spits this error out whenever it receives a connection from this version of xdebug.

```
$php -v
PHP 7.0.12 (cli) (built: Nov  8 2016 23:44:58) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0rc1, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ cat launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```

**Comment by felixfbecker** [comment]
It's because of the RC version - in latest master semver is not used anymore, so could you try that out?

**Comment by bunchjesse** [comment]
You mean `2.4.1`?

**Comment by felixfbecker** [comment]
Either use 2.4.1 from XDebug or try the `master` branch from this extension

**Comment by bunchjesse** [comment]
I see. Thanks. Using 2.4.1 did in fact fix the issue. It is my understanding that future versions of this plugin will support the RC versions? Or, should we always use the GM builds?

**Comment by felixfbecker** [comment]
It is just a bug with parsing the version number. Future releases will support them.

**Comment by maaarghk** [comment]
If it worked on master yesterday, will it work on 1.10.0 today?

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/vscode-php-debug/commits/master
