### ISSUE TITLE
Crash while debugging adapter - dbgp.ts:42 "Undefined is not a function"

### ISSUE THREAD

**Issue by AndrewNatoli** [felixfbecker/vscode-php-debug#9]
Hey Felix, this might be related to your issue here https://github.com/Microsoft/vscode-debugadapter-node/issues/7. 

When I debug the extension and send it an xdebug connection it breaks at line 42 of `dbgp.ts`.

```
41 // does data contain a NULL byte?
42 const nullByteIndex = data.indexOf(0);
```

Here's a (truncated) look at `data`
![screen shot 2016-01-09 at 4 47 49 pm](https://cloud.githubusercontent.com/assets/4162073/12218559/d4aa4a98-b6f0-11e5-80c2-908d649e8240.png)

Full exception is...
```
/lowercase/vscode-php-debug/out/dbgp.js:33
            var nullByteIndex = data.indexOf(0);
                                     ^
TypeError: undefined is not a function
    at Connection.DbgpConnection._handleDataChunk (/lowercase/vscode-php-debug/out/dbgp.js:33:38)
    at Socket.<anonymous> (/lowercase/vscode-php-debug/out/dbgp.js:26:58)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

From there the adapter debugger quits and the extension development host window's debugger becomes unresponsive.

**Comment by felixfbecker** [comment]
Now THAT is an interesting catch. `indexOf` is part of the [Node Buffer API](https://nodejs.org/docs/v4.1.1/api/buffer.html#buffer_buf_indexof_value_byteoffset).
Could you please check what Node version Code runs on by going to Help, About? For me, it is 4.1.1 (even though I have 5.3 installed) and 4.1.1 definitely has `Buffer.prototype.indexOf`.

**Comment by AndrewNatoli** [comment]
Ahhh look at me running 0.12.7. While my about window doesn't mention the version of Node being used (it's a little barren on OSX; see below), I upgraded to 4.1.1 and this isn't an issue anymore. Sorry for the mistake; I'm wandering around uncharted territory to me. That said, debugging the adapter *does* seem to work for me so feel free to ask if you need me to check on anything. 

![screen shot 2016-01-09 at 5 14 51 pm](https://cloud.githubusercontent.com/assets/4162073/12218664/8cd8bf7a-b6f4-11e5-923d-97ea4a45086b.png)

**Comment by felixfbecker** [comment]
Maybe we can add a `node` version to the `engines` in the package.json? I just don't know if VS Code actually respects that setting. Will do it nevertheless.
