### ISSUE TITLE
Run launched debugging requests scripts in the scripts directory, not workspace directory

### ISSUE THREAD

**Issue by trymeouteh** [felixfbecker/vscode-php-debug#973]
PHP version: 8.1.2
Xdebug version: 3.1.2
VS Code extension version: 1.35.0

Your launch.json:

```
			{
				"name": "PHP:CLI",
				"type": "php",
				"request": "launch",
				"program": "${file}",
				"runtimeArgs": ["-d xdebug.start_with_request=yes"]
			},
```

Xdebug php.ini config:

```
xdebug.mode=debug
```

Debug Console:

```
PHP Warning:  require(../a.php): Failed to open stream: No such file or directory in /home/John/Desktop/test/folder/b.php on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '../a.php' (include_path='.:/usr/share/php') in /home/john/Desktop/test/folder/b.php:3
Stack trace:
#0 {main}
  thrown in /home/john/Desktop/test/folder/b.php on line 3
```

Code snippet to reproduce:

```
- a.php
- folder/
   - b.php
```

```
//a.php
<?php

echo 'a';
echo PHP_EOL;
```

```
//b.php
<?php

require '../a.php';

echo 'b';
echo PHP_EOL;
```

The debugger is unable to debug script that are inside a child directory in the workspace directory. When you run `php folder/b.php` you will get the same error since PHP cannot read files from the parent directory. However when you run...

```
cd folder
php b.php
```

these commands by moving into the `folder` directory and then running the script it will work.

I would like to suggest this extension when using a launch request, to always run the script in the debugger from its directory. Therefore when the debugger is launched it will run...

```
cd folder
php b.php -d xdebug.start_with_request=yes
```

Instead of `php folder/b.php -d xdebug.start_with_request=yes`

**Comment by zobo** [comment]
It's custom to take the current process working directory if it's not specified. If you'd like to change the current working directory, you can do so with the `cwd` attribute in `launch.json`. See [Launch.json attributes](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) and [Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables).  I think what you need is:

```json
			{
				"name": "PHP:CLI",
				"type": "php",
				"request": "launch",
				"program": "${file}",
				"cwd": "${fileDirname}",
				"runtimeArgs": ["-d xdebug.start_with_request=yes"]
			},
```
